In [ ]:
import helpy
import pandas as pd
from single_analysis import Analysis
import warnings
from sklearn.exceptions import ConvergenceWarning
from pandas.errors import PerformanceWarning

warnings.filterwarnings("ignore", category=ConvergenceWarning)
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=PerformanceWarning)

pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)

In [2]:
analysis_df = helpy.get_analysis_df(.08, 100, 3)

In [3]:
# list of models to test effectiveness of
training_range = (2007, 2020)
testing_range = (2021, 2025)

base_analysis = Analysis(analysis_df, training_range=training_range, testing_range=testing_range, config_file='all_predictor_tuning.json')


base_analysis.get_predictors()

In [4]:
base_analysis.predictors

{'Residuals': <fip_predictor.FIP_Predictor at 0x7928643673e0>,
 'Usage': <fip_predictor.FIP_Predictor at 0x7928bde79700>,
 'Regular Movement': <fip_predictor.FIP_Predictor at 0x79286bb0fc50>,
 'Baseline': <fip_predictor.FIP_Predictor at 0x7928643def60>,
 'No FIP': <fip_predictor.FIP_Predictor at 0x7928643ddd30>,
 'Velo + FIP': <fip_predictor.FIP_Predictor at 0x7928643deb40>}

In [5]:
base_analysis.predictor_results.sort_values('R2', ascending=False)

          Feature Set          Model        MAE       RMSE        R2
279  Regular Movement    Elastic Net  12.111350  15.197268  0.279666
5           Residuals    Elastic Net  12.110159  15.198503  0.279549
278  Regular Movement    Elastic Net  12.113384  15.199402  0.279464
4           Residuals    Elastic Net  12.111387  15.199844  0.279422
3           Residuals    Elastic Net  12.113019  15.201367  0.279278
..                ...            ...        ...        ...       ...
500          Baseline  Random Forest  14.456778  17.966836 -0.006806
520          Baseline  Random Forest  14.477709  17.996700 -0.010156
529          Baseline  Random Forest  14.560944  18.094941 -0.021215
509          Baseline  Random Forest  14.601193  18.110651 -0.022989
451          Baseline        XGBoost  14.738475  18.427559 -0.059103

[822 rows x 5 columns]

In [6]:
base_analysis.get_lppm_scores()

In [7]:
base_analysis.results_df

,PlayerName,Season,FIP-,ERA-,pivFA,...,Velo + FIP48_rf_score,pred_Velo + FIP49_rf,Velo + FIP49_rf_score,pred_Velo + FIP0_gam,Velo + FIP0_gam_score
18,Aaron Civale,2021,114.279639,90.588031,91.495320,...,4.875196,106.025255,4.237928,110.070299,0.192884
19,Aaron Civale,2023,84.753358,82.963375,91.925195,...,1.920915,91.780151,0.144757,93.723429,-1.798521
20,Aaron Civale,2024,118.198572,110.490439,92.110243,...,0.711521,111.129906,-3.424047,106.553209,1.152650
21,Aaron Civale,2025,110.313836,118.279832,92.038485,...,-2.488626,112.335855,-6.018885,105.747393,0.569577
48,Aaron Nola,2021,77.268658,109.811032,93.058178,...,-1.657932,90.996988,-1.267657,88.380667,1.348664
...,...,...,...,...,...,...,...,...,...,...,...
3632,Zack Wheeler,2021,59.142138,65.997313,97.335892,...,1.713882,76.723673,0.395606,73.858020,3.261259
3633,Zack Wheeler,2022,71.175719,69.673653,96.103651,...,4.428255,79.376570,2.280495,78.546404,3.110662
3634,Zack Wheeler,2023,70.699745,81.310410,95.962228,...,3.389567,77.541994,3.793497,78.018913,3.316579
3635,Zack Wheeler,2024,75.354912,60.249158,95.467899,...,-0.471493,80.689134,7.332124,84.393429,3.627829
3636,Zack Wheeler,2025,71.192625,62.285198,95.976506,...,-1.928704,86.026585,-0.493637,83.453875,2.079073

In [8]:
base_analysis.get_model_metrics()

              Model    N  Breakouts   ROC-AUC    PR-AUC
0       No FIP11_en  458        133  0.730827  0.577551
1        No FIP5_en  458        133  0.730480  0.576525
2        No FIP4_en  458        133  0.730411  0.576367
3        No FIP9_en  458        133  0.730503  0.576221
4        No FIP3_en  458        133  0.730480  0.576170
..              ...  ...        ...       ...       ...
817   Baseline0_gam  458        133  0.500000  0.290393
818  Baseline36_xgb  458        133  0.490388  0.288909
819  Baseline30_xgb  458        133  0.479792  0.274280
820  Baseline48_xgb  458        133  0.469057  0.274277
821  Baseline29_xgb  458        133  0.477548  0.271881

[822 rows x 5 columns]

In [9]:
base_analysis.results_df[['PlayerName', 'Season', 'No FIP11_en_score', 'FIP-', 'led_to_breakout']].sort_values('No FIP11_en_score', ascending=False)

           PlayerName  Season  No FIP11_en_score        FIP-  led_to_breakout
1157   Gavin Williams    2025          19.472610  107.075247             True
2305   MacKenzie Gore    2023          19.226406  111.273603             True
3126        Shane Baz    2025          19.066808  103.954689             True
505      Carlos Rodón    2024          18.340804  104.992095             True
1269    Hunter Greene    2022          17.755135  102.804968             True
...               ...     ...                ...         ...              ...
696   Clayton Kershaw    2022         -18.280509   63.841059            False
639        Chris Sale    2024         -18.366917   52.975101            False
2506     Michael King    2023         -19.221803   71.702132            False
3194  Spencer Strider    2022         -23.613879   47.624203            False
747     Corbin Burnes    2021         -26.364816   37.560553            False

[458 rows x 5 columns]

In [10]:
helpy.breakout_rate_suite(base_analysis.results_df, 'No FIP11_en_score', 'led_to_breakout')

Overall Breakout Rate: 29.04%
Top 5% Breakout Rate: 81.82%
Top 10% Breakout Rate: 66.67%
Top 25% Breakout Rate: 56.14%
Top 50% Breakout Rate: 42.36%

In [11]:
baseline_scores_df = helpy.create_baseline_breakout_model(analysis_df, training_range, testing_range)

In [12]:
baseline_scores_df[['score_fip', 'FIP-', 'led_to_breakout']].sort_values('score_fip', ascending=False)

      score_fip        FIP-  led_to_breakout
3165   0.443510  119.136311            False
139    0.443506  119.210677             True
215    0.443506  118.807209            False
2513   0.443500  119.299546            False
1325   0.443480  119.480978            False
...         ...         ...              ...
2850   0.227167   62.124544            False
1139   0.226949   63.995447            False
2037   0.226942   63.121288            False
696    0.226934   63.841059            False
49     0.226925   63.712463            False

[458 rows x 3 columns]

In [13]:
helpy.breakout_rate_suite(baseline_scores_df, 'score_fip', 'led_to_breakout')

Overall Breakout Rate: 29.04%
Top 5% Breakout Rate: 27.27%
Top 10% Breakout Rate: 42.22%
Top 25% Breakout Rate: 45.61%
Top 50% Breakout Rate: 38.86%

In [14]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [15]:
two_year_breakout_df = helpy.is_breakout(base_analysis.results_df, .08, 100, 3)
base_analysis.get_model_metrics(df=two_year_breakout_df)

                      Model    N  Breakouts   ROC-AUC    PR-AUC
0               No FIP11_en  458        133  0.730827  0.577551
1                No FIP5_en  458        133  0.730480  0.576525
2                No FIP4_en  458        133  0.730411  0.576367
3                No FIP9_en  458        133  0.730503  0.576221
4                No FIP3_en  458        133  0.730480  0.576170
5               No FIP10_en  458        133  0.730711  0.575999
6                No FIP2_en  458        133  0.730411  0.575932
7                No FIP1_en  458        133  0.730295  0.575375
8                No FIP0_en  458        133  0.730156  0.575018
9               No FIP17_en  458        133  0.725807  0.572024
10               No FIP8_en  458        133  0.729023  0.571662
11               No FIP7_en  458        133  0.728305  0.568903
12               No FIP6_en  458        133  0.727843  0.567075
13              No FIP16_en  458        133  0.720463  0.559803
14             No FIP21_xgb  458        133  0.732331  0.556922
15             No FIP19_xgb  458        133  0.735685  0.552253
16             No FIP26_xgb  458        133  0.730110  0.551067
17             No FIP34_xgb  458        133  0.734945  0.549346
18              No FIP15_en  458        133  0.716044  0.546469
19           Residuals27_rf  458        133  0.730064  0.545419
20          Velo + FIP18_en  458        133  0.677224  0.544887
21             No FIP15_xgb  458        133  0.730966  0.543409
22             No FIP39_xgb  458        133  0.723887  0.542532
23             No FIP44_xgb  458        133  0.724766  0.542517
24              No FIP46_rf  458        133  0.726987  0.539463
25              No FIP24_rf  458        133  0.726293  0.538339
26              No FIP14_en  458        133  0.712620  0.535735
27              No FIP30_rf  458        133  0.725575  0.535635
28           Residuals24_rf  458        133  0.727033  0.535189
29           Residuals30_rf  458        133  0.727750  0.534798
30           Residuals29_rf  458        133  0.717363  0.533751
31              No FIP27_rf  458        133  0.726270  0.532719
32          Residuals21_xgb  458        133  0.716113  0.532623
33             No FIP45_xgb  458        133  0.727565  0.532206
34             No FIP29_xgb  458        133  0.730665  0.531890
35              No FIP13_en  458        133  0.711209  0.531615
36              No FIP41_rf  458        133  0.725853  0.531553
37              No FIP12_en  458        133  0.710307  0.530161
38          Velo + FIP19_en  458        133  0.672296  0.529289
39    Regular Movement18_en  458        133  0.679190  0.529159
40              No FIP3_xgb  458        133  0.723956  0.527969
41              No FIP7_xgb  458        133  0.720139  0.527632
42              No FIP36_rf  458        133  0.723540  0.526745
43           Residuals41_rf  458        133  0.717178  0.526197
44    Regular Movement19_en  458        133  0.675882  0.526134
45              No FIP11_rf  458        133  0.725761  0.525503
46               No FIP5_rf  458        133  0.721619  0.523890
47             No FIP48_xgb  458        133  0.725205  0.523539
48              No FIP29_rf  458        133  0.722984  0.523062
49            Residuals5_rf  458        133  0.723771  0.522922
50              No FIP40_rf  458        133  0.718820  0.522775
51             No FIP49_xgb  458        133  0.724049  0.522275
52           Residuals46_rf  458        133  0.721249  0.522234
53              No FIP18_rf  458        133  0.724881  0.521938
54             No FIP12_xgb  458        133  0.713060  0.521163
55                Usage5_rf  458        133  0.697698  0.520390
56           Residuals25_rf  458        133  0.707368  0.519863
57           Residuals18_rf  458        133  0.717085  0.519499
58           Residuals36_rf  458        133  0.716044  0.517767
59              No FIP44_rf  458        133  0.718334  0.517422
60    Regular Movement46_rf  458        133  0.711163  0.517391
61           Residuals18_en  458        133  0.699433  0.516515
62              No FIP26_rf  458        133  0.716761  0.516001
63           Residuals7_xgb  458        133  0.713962  0.515906
64    Regular Movement30_rf  458        133  0.713360  0.515401
65               No FIP1_rf  458        133  0.713013  0.515294
66          Residuals12_xgb  458        133  0.696264  0.515091
67               Usage11_rf  458        133  0.685807  0.514963
68             No FIP22_xgb  458        133  0.715350  0.514508
69              No FIP12_rf  458        133  0.712805  0.513971
70             No FIP30_xgb  458        133  0.726385  0.513392
71    Regular Movement24_rf  458        133  0.715095  0.513389
72              No FIP13_rf  458        133  0.717895  0.513103
73              No FIP15_rf  458        133  0.719792  0.512614
74             No FIP36_xgb  458        133  0.719098  0.511407
75            Baseline18_en  458        133  0.673383  0.511294
76             No FIP47_xgb  458        133  0.720740  0.510469
77           Residuals19_en  458        133  0.695824  0.509746
78              No FIP47_rf  458        133  0.721342  0.509703
79              No FIP17_rf  458        133  0.707669  0.508809
80               Usage27_rf  458        133  0.693418  0.508689
81              No FIP37_rf  458        133  0.693742  0.508590
82               Usage46_rf  458        133  0.699132  0.508498
83               No FIP8_rf  458        133  0.716669  0.507710
84               Usage20_en  458        133  0.668988  0.507388
85              No FIP9_xgb  458        133  0.703112  0.507129
86              No FIP43_rf  458        133  0.718080  0.507070
87             No FIP40_xgb  458        133  0.727935  0.506904
88              No FIP8_xgb  458        133  0.703621  0.506072
89          Velo + FIP7_xgb  458        133  0.697698  0.506019
90              No FIP19_rf  458        133  0.718034  0.505909
91              No FIP48_rf  458        133  0.714841  0.504192
92    Regular Movement27_rf  458        133  0.712435  0.504009
93           Residuals44_rf  458        133  0.701885  0.503921
94              No FIP31_rf  458        133  0.712227  0.503812
95               No FIP7_rf  458        133  0.702718  0.503723
96              No FIP38_rf  458        133  0.710121  0.503716
97             No FIP35_xgb  458        133  0.712204  0.503387
98          Residuals39_xgb  458        133  0.699595  0.503104
99              No FIP14_rf  458        133  0.713222  0.502899
100   Regular Movement11_rf  458        133  0.698161  0.502839
101             No FIP2_xgb  458        133  0.712019  0.502803
102   Regular Movement41_rf  458        133  0.702441  0.502392
103             No FIP1_xgb  458        133  0.709173  0.501188
104          Residuals20_en  458        133  0.689971  0.500824
105          Residuals15_rf  458        133  0.705240  0.500672
106            No FIP27_xgb  458        133  0.702233  0.500297
107    Regular Movement5_rf  458        133  0.712689  0.499981
108          Residuals11_rf  458        133  0.717617  0.499442
109            No FIP14_xgb  458        133  0.706189  0.499293
110             No FIP35_rf  458        133  0.695153  0.499188
111          Residuals40_rf  458        133  0.702140  0.499112
112   Regular Movement7_xgb  458        133  0.704615  0.498823
113             No FIP25_rf  458        133  0.715998  0.498645
114             Usage44_xgb  458        133  0.686131  0.498032
115           Baseline19_en  458        133  0.670376  0.497623
116         Velo + FIP30_rf  458        133  0.695408  0.497531
117   Regular Movement20_en  458        133  0.666698  0.497325
118              No FIP4_rf  458        133  0.694829  0.497187
119              No FIP6_rf  458        133  0.693117  0.496759
120              Usage36_rf  458        133  0.676252  0.496676
121    Regular Movement1_en  458        133  0.691012  0.496460
122    Regular Movement0_en  458        133  0.690966  0.496329
123          Residuals8_xgb  458        133  0.689994  0.496128
124             No FIP20_rf  458        133  0.710677  0.496115
125    Regular Movement8_en  458        133  0.690156  0.495764
126              Usage7_xgb  458        133  0.688143  0.495741
127    Regular Movement2_en  458        133  0.690110  0.495670
128             No FIP34_rf  458        133  0.701492  0.495202
129   Regular Movement10_en  458        133  0.691035  0.495161
130             Usage39_xgb  458        133  0.683169  0.495113
131             No FIP39_rf  458        133  0.706212  0.494593
132    Regular Movement9_en  458        133  0.690549  0.494285
133         Velo + FIP20_en  458        133  0.663274  0.494137
134              Usage18_rf  458        133  0.671139  0.494104
135    Regular Movement3_en  458        133  0.689508  0.494004
136            No FIP16_xgb  458        133  0.711116  0.493960
137    Regular Movement5_en  458        133  0.689370  0.493665
138              Usage30_rf  458        133  0.689717  0.493531
139           Residuals7_en  458        133  0.695639  0.493498
140          Residuals11_en  458        133  0.693742  0.493382
141           Residuals8_en  458        133  0.694806  0.493358
142             No FIP49_rf  458        133  0.698647  0.493274
143    Regular Movement4_en  458        133  0.689161  0.493203
144          Residuals10_en  458        133  0.694459  0.493061
145    Regular Movement7_en  458        133  0.689069  0.493039
146           Residuals9_en  458        133  0.695014  0.492766
147           Residuals1_en  458        133  0.690411  0.492609
148           Residuals4_en  458        133  0.689601  0.492562
149           Residuals6_en  458        133  0.695940  0.492507
150            No FIP32_xgb  458        133  0.710029  0.492477
151   Regular Movement36_rf  458        133  0.702556  0.492413
152             No FIP32_rf  458        133  0.709520  0.492402
153           Residuals5_en  458        133  0.689370  0.492386
154           Residuals2_en  458        133  0.690040  0.492326
155              No FIP3_rf  458        133  0.711255  0.492303
156           Residuals3_en  458        133  0.689693  0.492189
157          Residuals17_en  458        133  0.693210  0.492111
158            No FIP33_xgb  458        133  0.714633  0.492000
159          Residuals48_rf  458        133  0.704130  0.491981
160           Residuals0_en  458        133  0.690457  0.491941
161    Regular Movement6_en  458        133  0.688329  0.491650
162              Usage41_rf  458        133  0.676969  0.491340
163              Usage24_rf  458        133  0.694436  0.491332
164              Usage21_en  458        133  0.661955  0.491152
165   Regular Movement11_en  458        133  0.690804  0.491070
166             No FIP45_rf  458        133  0.704430  0.490480
167              Usage29_rf  458        133  0.670029  0.490292
168        Velo + FIP44_xgb  458        133  0.689416  0.490231
169            No FIP17_xgb  458        133  0.728375  0.489978
170         Residuals34_xgb  458        133  0.703597  0.489854
171          Residuals21_en  458        133  0.677872  0.489847
172             No FIP22_rf  458        133  0.689393  0.489766
173         Residuals45_xgb  458        133  0.711232  0.489021
174         Velo + FIP27_rf  458        133  0.694853  0.488656
175             Usage14_xgb  458        133  0.684072  0.488526
176              Usage15_rf  458        133  0.675789  0.488516
177             No FIP42_rf  458        133  0.687658  0.487498
178        Velo + FIP14_xgb  458        133  0.690920  0.487454
179         Residuals26_xgb  458        133  0.694737  0.486827
180  Regular Movement39_xgb  458        133  0.685784  0.486749
181              No FIP9_rf  458        133  0.684187  0.485874
182             No FIP16_rf  458        133  0.697559  0.485852
183          Residuals16_en  458        133  0.693210  0.485470
184         Residuals14_xgb  458        133  0.700197  0.485362
185   Regular Movement13_rf  458        133  0.696079  0.485233
186        Velo + FIP39_xgb  458        133  0.682013  0.485008
187   Regular Movement29_rf  458        133  0.702603  0.484955
188             No FIP18_en  458        133  0.689184  0.484497
189             No FIP23_rf  458        133  0.708618  0.484471
190          Residuals26_rf  458        133  0.693071  0.484404
191              Usage19_en  458        133  0.670654  0.484340
192            No FIP37_xgb  458        133  0.705911  0.484177
193           Baseline20_en  458        133  0.664083  0.484029
194             No FIP10_rf  458        133  0.688213  0.483722
195          Residuals47_rf  458        133  0.701423  0.483297
196              Usage13_rf  458        133  0.665333  0.483233
197            No FIP31_xgb  458        133  0.697444  0.482558
198             Usage34_xgb  458        133  0.644419  0.482505
199            No FIP18_xgb  458        133  0.707530  0.482331
200           Residuals8_rf  458        133  0.688282  0.482320
201              No FIP2_rf  458        133  0.696958  0.482149
202              Usage48_rf  458        133  0.663181  0.481667
203  Regular Movement21_xgb  458        133  0.697351  0.481352
204             No FIP28_rf  458        133  0.684673  0.481072
205         Velo + FIP46_rf  458        133  0.691452  0.480542
206         Velo + FIP41_rf  458        133  0.679722  0.480344
207         Velo + FIP8_xgb  458        133  0.686478  0.479664
208         Velo + FIP1_xgb  458        133  0.682360  0.479450
209              Usage8_xgb  458        133  0.681411  0.479354
210          Residuals15_en  458        133  0.693488  0.479275
211         Velo + FIP18_rf  458        133  0.681712  0.478949
212             Usage21_xgb  458        133  0.670052  0.478801
213            No FIP10_xgb  458        133  0.690781  0.478370
214          Residuals12_en  458        133  0.696379  0.478274
215              Usage47_rf  458        133  0.663158  0.477677
216              No FIP0_rf  458        133  0.686316  0.477462
217   Regular Movement18_rf  458        133  0.700937  0.477453
218          Residuals13_en  458        133  0.696009  0.477199
219             No FIP33_rf  458        133  0.688005  0.476992
220   Regular Movement17_en  458        133  0.672527  0.476754
221         Velo + FIP25_rf  458        133  0.676252  0.476620
222          Residuals14_rf  458        133  0.698832  0.476548
223             No FIP19_en  458        133  0.688560  0.476487
224             Usage26_xgb  458        133  0.668826  0.475979
225              Usage12_rf  458        133  0.663135  0.475250
226          Residuals22_en  458        133  0.662533  0.475245
227  Regular Movement14_xgb  458        133  0.693765  0.474640
228   Regular Movement25_rf  458        133  0.696888  0.474489
229         Velo + FIP11_rf  458        133  0.681064  0.474384
230   Regular Movement8_xgb  458        133  0.683516  0.473690
231             No FIP0_gam  458        133  0.690017  0.473576
232          Residuals14_en  458        133  0.693279  0.473149
233   Regular Movement15_rf  458        133  0.691452  0.473021
234          Residuals23_rf  458        133  0.693094  0.472881
235   Regular Movement16_en  458        133  0.667831  0.472784
236   Regular Movement15_en  458        133  0.666651  0.472290
237         Residuals44_xgb  458        133  0.687010  0.472268
238   Regular Movement13_en  458        133  0.669705  0.471754
239   Regular Movement12_en  458        133  0.670121  0.471676
240   Regular Movement14_en  458        133  0.668595  0.471623
241          Velo + FIP5_rf  458        133  0.689948  0.471508
242          Residuals1_xgb  458        133  0.690457  0.471158
243         Velo + FIP24_rf  458        133  0.690272  0.471114
244          Residuals13_rf  458        133  0.699040  0.470399
245            No FIP28_xgb  458        133  0.709427  0.470220
246   Regular Movement21_en  458        133  0.654737  0.470101
247              Usage18_en  458        133  0.671602  0.469964
248          Residuals3_xgb  458        133  0.681828  0.469805
249         Velo + FIP29_rf  458        133  0.675951  0.469362
250            No FIP20_xgb  458        133  0.699688  0.469342
251              Usage22_en  458        133  0.648861  0.468975
252         Velo + FIP21_en  458        133  0.652817  0.468818
253             No FIP21_rf  458        133  0.683239  0.468625
254          Residuals32_rf  458        133  0.683331  0.468559
255  Regular Movement12_xgb  458        133  0.680139  0.468343
256        Velo + FIP34_xgb  458        133  0.655963  0.468209
257        Velo + FIP12_xgb  458        133  0.663042  0.467939
258         Velo + FIP23_rf  458        133  0.657374  0.467761
259            No FIP41_xgb  458        133  0.713360  0.467553
260             No FIP21_en  458        133  0.686177  0.467487
261             No FIP20_en  458        133  0.686709  0.467399
262              Usage1_xgb  458        133  0.668271  0.465719
263             No FIP22_en  458        133  0.685737  0.465177
264   Regular Movement40_rf  458        133  0.678936  0.465125
265         Velo + FIP13_rf  458        133  0.675998  0.464326
266            No FIP24_xgb  458        133  0.699942  0.463455
267              Usage14_rf  458        133  0.656333  0.463086
268  Regular Movement44_xgb  458        133  0.675882  0.462970
269          Residuals20_rf  458        133  0.702834  0.462852
270           Baseline21_en  458        133  0.650966  0.462768
271              Usage40_rf  458        133  0.647287  0.462349
272             No FIP23_en  458        133  0.685252  0.462213
273          Residuals19_rf  458        133  0.681272  0.462188
274   Regular Movement47_rf  458        133  0.687704  0.461565
275             Usage45_xgb  458        133  0.656750  0.461369
276   Regular Movement26_rf  458        133  0.678311  0.461159
277              Usage25_rf  458        133  0.657559  0.461082
278        Velo + FIP26_xgb  458        133  0.663852  0.461078
279              Usage3_xgb  458        133  0.640301  0.460684
280         Velo + FIP36_rf  458        133  0.673198  0.460407
281              Usage44_rf  458        133  0.649763  0.460083
282             No FIP6_xgb  458        133  0.704916  0.459543
283             No FIP5_xgb  458        133  0.684326  0.459044
284             Usage12_xgb  458        133  0.651822  0.458036
285           Residuals1_rf  458        133  0.675766  0.457675
286              Usage43_rf  458        133  0.651567  0.457673
287   Regular Movement1_xgb  458        133  0.683285  0.457479
288          Residuals23_en  458        133  0.646431  0.456915
289              Usage20_rf  458        133  0.643771  0.456767
290               Usage3_rf  458        133  0.658855  0.456443
291  Regular Movement26_xgb  458        133  0.668109  0.455109
292              Usage26_rf  458        133  0.654598  0.454584
293              Usage19_rf  458        133  0.657744  0.454289
294         Velo + FIP15_rf  458        133  0.670977  0.453893
295         Velo + FIP17_en  458        133  0.640000  0.453772
296          Residuals17_rf  458        133  0.666142  0.453274
297   Regular Movement44_rf  458        133  0.677663  0.453111
298              Usage23_rf  458        133  0.639722  0.452242
299            No FIP13_xgb  458        133  0.699364  0.452089
300           Residuals7_rf  458        133  0.664916  0.451671
301          Residuals43_rf  458        133  0.687172  0.451481
302        Velo + FIP45_xgb  458        133  0.661793  0.451230
303         Velo + FIP20_rf  458        133  0.656194  0.450940
304              Usage9_xgb  458        133  0.645529  0.450881
305         Velo + FIP3_xgb  458        133  0.650758  0.450642
306   Regular Movement22_en  458        133  0.641180  0.449089
307         Velo + FIP22_en  458        133  0.641180  0.449089
308          Residuals31_rf  458        133  0.678010  0.448688
309          Residuals24_en  458        133  0.669011  0.448539
310          Residuals25_en  458        133  0.665957  0.447439

In [16]:
one_year_breakout_df = helpy.is_breakout(base_analysis.results_df, .08, 100, 3)
base_analysis.get_model_metrics(df=one_year_breakout_df)

                      Model    N  Breakouts   ROC-AUC    PR-AUC
0               No FIP11_en  458        133  0.730827  0.577551
1                No FIP5_en  458        133  0.730480  0.576525
2                No FIP4_en  458        133  0.730411  0.576367
3                No FIP9_en  458        133  0.730503  0.576221
4                No FIP3_en  458        133  0.730480  0.576170
5               No FIP10_en  458        133  0.730711  0.575999
6                No FIP2_en  458        133  0.730411  0.575932
7                No FIP1_en  458        133  0.730295  0.575375
8                No FIP0_en  458        133  0.730156  0.575018
9               No FIP17_en  458        133  0.725807  0.572024
10               No FIP8_en  458        133  0.729023  0.571662
11               No FIP7_en  458        133  0.728305  0.568903
12               No FIP6_en  458        133  0.727843  0.567075
13              No FIP16_en  458        133  0.720463  0.559803
14             No FIP21_xgb  458        133  0.732331  0.556922
15             No FIP19_xgb  458        133  0.735685  0.552253
16             No FIP26_xgb  458        133  0.730110  0.551067
17             No FIP34_xgb  458        133  0.734945  0.549346
18              No FIP15_en  458        133  0.716044  0.546469
19           Residuals27_rf  458        133  0.730064  0.545419
20          Velo + FIP18_en  458        133  0.677224  0.544887
21             No FIP15_xgb  458        133  0.730966  0.543409
22             No FIP39_xgb  458        133  0.723887  0.542532
23             No FIP44_xgb  458        133  0.724766  0.542517
24              No FIP46_rf  458        133  0.726987  0.539463
25              No FIP24_rf  458        133  0.726293  0.538339
26              No FIP14_en  458        133  0.712620  0.535735
27              No FIP30_rf  458        133  0.725575  0.535635
28           Residuals24_rf  458        133  0.727033  0.535189
29           Residuals30_rf  458        133  0.727750  0.534798
30           Residuals29_rf  458        133  0.717363  0.533751
31              No FIP27_rf  458        133  0.726270  0.532719
32          Residuals21_xgb  458        133  0.716113  0.532623
33             No FIP45_xgb  458        133  0.727565  0.532206
34             No FIP29_xgb  458        133  0.730665  0.531890
35              No FIP13_en  458        133  0.711209  0.531615
36              No FIP41_rf  458        133  0.725853  0.531553
37              No FIP12_en  458        133  0.710307  0.530161
38          Velo + FIP19_en  458        133  0.672296  0.529289
39    Regular Movement18_en  458        133  0.679190  0.529159
40              No FIP3_xgb  458        133  0.723956  0.527969
41              No FIP7_xgb  458        133  0.720139  0.527632
42              No FIP36_rf  458        133  0.723540  0.526745
43           Residuals41_rf  458        133  0.717178  0.526197
44    Regular Movement19_en  458        133  0.675882  0.526134
45              No FIP11_rf  458        133  0.725761  0.525503
46               No FIP5_rf  458        133  0.721619  0.523890
47             No FIP48_xgb  458        133  0.725205  0.523539
48              No FIP29_rf  458        133  0.722984  0.523062
49            Residuals5_rf  458        133  0.723771  0.522922
50              No FIP40_rf  458        133  0.718820  0.522775
51             No FIP49_xgb  458        133  0.724049  0.522275
52           Residuals46_rf  458        133  0.721249  0.522234
53              No FIP18_rf  458        133  0.724881  0.521938
54             No FIP12_xgb  458        133  0.713060  0.521163
55                Usage5_rf  458        133  0.697698  0.520390
56           Residuals25_rf  458        133  0.707368  0.519863
57           Residuals18_rf  458        133  0.717085  0.519499
58           Residuals36_rf  458        133  0.716044  0.517767
59              No FIP44_rf  458        133  0.718334  0.517422
60    Regular Movement46_rf  458        133  0.711163  0.517391
61           Residuals18_en  458        133  0.699433  0.516515
62              No FIP26_rf  458        133  0.716761  0.516001
63           Residuals7_xgb  458        133  0.713962  0.515906
64    Regular Movement30_rf  458        133  0.713360  0.515401
65               No FIP1_rf  458        133  0.713013  0.515294
66          Residuals12_xgb  458        133  0.696264  0.515091
67               Usage11_rf  458        133  0.685807  0.514963
68             No FIP22_xgb  458        133  0.715350  0.514508
69              No FIP12_rf  458        133  0.712805  0.513971
70             No FIP30_xgb  458        133  0.726385  0.513392
71    Regular Movement24_rf  458        133  0.715095  0.513389
72              No FIP13_rf  458        133  0.717895  0.513103
73              No FIP15_rf  458        133  0.719792  0.512614
74             No FIP36_xgb  458        133  0.719098  0.511407
75            Baseline18_en  458        133  0.673383  0.511294
76             No FIP47_xgb  458        133  0.720740  0.510469
77           Residuals19_en  458        133  0.695824  0.509746
78              No FIP47_rf  458        133  0.721342  0.509703
79              No FIP17_rf  458        133  0.707669  0.508809
80               Usage27_rf  458        133  0.693418  0.508689
81              No FIP37_rf  458        133  0.693742  0.508590
82               Usage46_rf  458        133  0.699132  0.508498
83               No FIP8_rf  458        133  0.716669  0.507710
84               Usage20_en  458        133  0.668988  0.507388
85              No FIP9_xgb  458        133  0.703112  0.507129
86              No FIP43_rf  458        133  0.718080  0.507070
87             No FIP40_xgb  458        133  0.727935  0.506904
88              No FIP8_xgb  458        133  0.703621  0.506072
89          Velo + FIP7_xgb  458        133  0.697698  0.506019
90              No FIP19_rf  458        133  0.718034  0.505909
91              No FIP48_rf  458        133  0.714841  0.504192
92    Regular Movement27_rf  458        133  0.712435  0.504009
93           Residuals44_rf  458        133  0.701885  0.503921
94              No FIP31_rf  458        133  0.712227  0.503812
95               No FIP7_rf  458        133  0.702718  0.503723
96              No FIP38_rf  458        133  0.710121  0.503716
97             No FIP35_xgb  458        133  0.712204  0.503387
98          Residuals39_xgb  458        133  0.699595  0.503104
99              No FIP14_rf  458        133  0.713222  0.502899
100   Regular Movement11_rf  458        133  0.698161  0.502839
101             No FIP2_xgb  458        133  0.712019  0.502803
102   Regular Movement41_rf  458        133  0.702441  0.502392
103             No FIP1_xgb  458        133  0.709173  0.501188
104          Residuals20_en  458        133  0.689971  0.500824
105          Residuals15_rf  458        133  0.705240  0.500672
106            No FIP27_xgb  458        133  0.702233  0.500297
107    Regular Movement5_rf  458        133  0.712689  0.499981
108          Residuals11_rf  458        133  0.717617  0.499442
109            No FIP14_xgb  458        133  0.706189  0.499293
110             No FIP35_rf  458        133  0.695153  0.499188
111          Residuals40_rf  458        133  0.702140  0.499112
112   Regular Movement7_xgb  458        133  0.704615  0.498823
113             No FIP25_rf  458        133  0.715998  0.498645
114             Usage44_xgb  458        133  0.686131  0.498032
115           Baseline19_en  458        133  0.670376  0.497623
116         Velo + FIP30_rf  458        133  0.695408  0.497531
117   Regular Movement20_en  458        133  0.666698  0.497325
118              No FIP4_rf  458        133  0.694829  0.497187
119              No FIP6_rf  458        133  0.693117  0.496759
120              Usage36_rf  458        133  0.676252  0.496676
121    Regular Movement1_en  458        133  0.691012  0.496460
122    Regular Movement0_en  458        133  0.690966  0.496329
123          Residuals8_xgb  458        133  0.689994  0.496128
124             No FIP20_rf  458        133  0.710677  0.496115
125    Regular Movement8_en  458        133  0.690156  0.495764
126              Usage7_xgb  458        133  0.688143  0.495741
127    Regular Movement2_en  458        133  0.690110  0.495670
128             No FIP34_rf  458        133  0.701492  0.495202
129   Regular Movement10_en  458        133  0.691035  0.495161
130             Usage39_xgb  458        133  0.683169  0.495113
131             No FIP39_rf  458        133  0.706212  0.494593
132    Regular Movement9_en  458        133  0.690549  0.494285
133         Velo + FIP20_en  458        133  0.663274  0.494137
134              Usage18_rf  458        133  0.671139  0.494104
135    Regular Movement3_en  458        133  0.689508  0.494004
136            No FIP16_xgb  458        133  0.711116  0.493960
137    Regular Movement5_en  458        133  0.689370  0.493665
138              Usage30_rf  458        133  0.689717  0.493531
139           Residuals7_en  458        133  0.695639  0.493498
140          Residuals11_en  458        133  0.693742  0.493382
141           Residuals8_en  458        133  0.694806  0.493358
142             No FIP49_rf  458        133  0.698647  0.493274
143    Regular Movement4_en  458        133  0.689161  0.493203
144          Residuals10_en  458        133  0.694459  0.493061
145    Regular Movement7_en  458        133  0.689069  0.493039
146           Residuals9_en  458        133  0.695014  0.492766
147           Residuals1_en  458        133  0.690411  0.492609
148           Residuals4_en  458        133  0.689601  0.492562
149           Residuals6_en  458        133  0.695940  0.492507
150            No FIP32_xgb  458        133  0.710029  0.492477
151   Regular Movement36_rf  458        133  0.702556  0.492413
152             No FIP32_rf  458        133  0.709520  0.492402
153           Residuals5_en  458        133  0.689370  0.492386
154           Residuals2_en  458        133  0.690040  0.492326
155              No FIP3_rf  458        133  0.711255  0.492303
156           Residuals3_en  458        133  0.689693  0.492189
157          Residuals17_en  458        133  0.693210  0.492111
158            No FIP33_xgb  458        133  0.714633  0.492000
159          Residuals48_rf  458        133  0.704130  0.491981
160           Residuals0_en  458        133  0.690457  0.491941
161    Regular Movement6_en  458        133  0.688329  0.491650
162              Usage41_rf  458        133  0.676969  0.491340
163              Usage24_rf  458        133  0.694436  0.491332
164              Usage21_en  458        133  0.661955  0.491152
165   Regular Movement11_en  458        133  0.690804  0.491070
166             No FIP45_rf  458        133  0.704430  0.490480
167              Usage29_rf  458        133  0.670029  0.490292
168        Velo + FIP44_xgb  458        133  0.689416  0.490231
169            No FIP17_xgb  458        133  0.728375  0.489978
170         Residuals34_xgb  458        133  0.703597  0.489854
171          Residuals21_en  458        133  0.677872  0.489847
172             No FIP22_rf  458        133  0.689393  0.489766
173         Residuals45_xgb  458        133  0.711232  0.489021
174         Velo + FIP27_rf  458        133  0.694853  0.488656
175             Usage14_xgb  458        133  0.684072  0.488526
176              Usage15_rf  458        133  0.675789  0.488516
177             No FIP42_rf  458        133  0.687658  0.487498
178        Velo + FIP14_xgb  458        133  0.690920  0.487454
179         Residuals26_xgb  458        133  0.694737  0.486827
180  Regular Movement39_xgb  458        133  0.685784  0.486749
181              No FIP9_rf  458        133  0.684187  0.485874
182             No FIP16_rf  458        133  0.697559  0.485852
183          Residuals16_en  458        133  0.693210  0.485470
184         Residuals14_xgb  458        133  0.700197  0.485362
185   Regular Movement13_rf  458        133  0.696079  0.485233
186        Velo + FIP39_xgb  458        133  0.682013  0.485008
187   Regular Movement29_rf  458        133  0.702603  0.484955
188             No FIP18_en  458        133  0.689184  0.484497
189             No FIP23_rf  458        133  0.708618  0.484471
190          Residuals26_rf  458        133  0.693071  0.484404
191              Usage19_en  458        133  0.670654  0.484340
192            No FIP37_xgb  458        133  0.705911  0.484177
193           Baseline20_en  458        133  0.664083  0.484029
194             No FIP10_rf  458        133  0.688213  0.483722
195          Residuals47_rf  458        133  0.701423  0.483297
196              Usage13_rf  458        133  0.665333  0.483233
197            No FIP31_xgb  458        133  0.697444  0.482558
198             Usage34_xgb  458        133  0.644419  0.482505
199            No FIP18_xgb  458        133  0.707530  0.482331
200           Residuals8_rf  458        133  0.688282  0.482320
201              No FIP2_rf  458        133  0.696958  0.482149
202              Usage48_rf  458        133  0.663181  0.481667
203  Regular Movement21_xgb  458        133  0.697351  0.481352
204             No FIP28_rf  458        133  0.684673  0.481072
205         Velo + FIP46_rf  458        133  0.691452  0.480542
206         Velo + FIP41_rf  458        133  0.679722  0.480344
207         Velo + FIP8_xgb  458        133  0.686478  0.479664
208         Velo + FIP1_xgb  458        133  0.682360  0.479450
209              Usage8_xgb  458        133  0.681411  0.479354
210          Residuals15_en  458        133  0.693488  0.479275
211         Velo + FIP18_rf  458        133  0.681712  0.478949
212             Usage21_xgb  458        133  0.670052  0.478801
213            No FIP10_xgb  458        133  0.690781  0.478370
214          Residuals12_en  458        133  0.696379  0.478274
215              Usage47_rf  458        133  0.663158  0.477677
216              No FIP0_rf  458        133  0.686316  0.477462
217   Regular Movement18_rf  458        133  0.700937  0.477453
218          Residuals13_en  458        133  0.696009  0.477199
219             No FIP33_rf  458        133  0.688005  0.476992
220   Regular Movement17_en  458        133  0.672527  0.476754
221         Velo + FIP25_rf  458        133  0.676252  0.476620
222          Residuals14_rf  458        133  0.698832  0.476548
223             No FIP19_en  458        133  0.688560  0.476487
224             Usage26_xgb  458        133  0.668826  0.475979
225              Usage12_rf  458        133  0.663135  0.475250
226          Residuals22_en  458        133  0.662533  0.475245
227  Regular Movement14_xgb  458        133  0.693765  0.474640
228   Regular Movement25_rf  458        133  0.696888  0.474489
229         Velo + FIP11_rf  458        133  0.681064  0.474384
230   Regular Movement8_xgb  458        133  0.683516  0.473690
231             No FIP0_gam  458        133  0.690017  0.473576
232          Residuals14_en  458        133  0.693279  0.473149
233   Regular Movement15_rf  458        133  0.691452  0.473021
234          Residuals23_rf  458        133  0.693094  0.472881
235   Regular Movement16_en  458        133  0.667831  0.472784
236   Regular Movement15_en  458        133  0.666651  0.472290
237         Residuals44_xgb  458        133  0.687010  0.472268
238   Regular Movement13_en  458        133  0.669705  0.471754
239   Regular Movement12_en  458        133  0.670121  0.471676
240   Regular Movement14_en  458        133  0.668595  0.471623
241          Velo + FIP5_rf  458        133  0.689948  0.471508
242          Residuals1_xgb  458        133  0.690457  0.471158
243         Velo + FIP24_rf  458        133  0.690272  0.471114
244          Residuals13_rf  458        133  0.699040  0.470399
245            No FIP28_xgb  458        133  0.709427  0.470220
246   Regular Movement21_en  458        133  0.654737  0.470101
247              Usage18_en  458        133  0.671602  0.469964
248          Residuals3_xgb  458        133  0.681828  0.469805
249         Velo + FIP29_rf  458        133  0.675951  0.469362
250            No FIP20_xgb  458        133  0.699688  0.469342
251              Usage22_en  458        133  0.648861  0.468975
252         Velo + FIP21_en  458        133  0.652817  0.468818
253             No FIP21_rf  458        133  0.683239  0.468625
254          Residuals32_rf  458        133  0.683331  0.468559
255  Regular Movement12_xgb  458        133  0.680139  0.468343
256        Velo + FIP34_xgb  458        133  0.655963  0.468209
257        Velo + FIP12_xgb  458        133  0.663042  0.467939
258         Velo + FIP23_rf  458        133  0.657374  0.467761
259            No FIP41_xgb  458        133  0.713360  0.467553
260             No FIP21_en  458        133  0.686177  0.467487
261             No FIP20_en  458        133  0.686709  0.467399
262              Usage1_xgb  458        133  0.668271  0.465719
263             No FIP22_en  458        133  0.685737  0.465177
264   Regular Movement40_rf  458        133  0.678936  0.465125
265         Velo + FIP13_rf  458        133  0.675998  0.464326
266            No FIP24_xgb  458        133  0.699942  0.463455
267              Usage14_rf  458        133  0.656333  0.463086
268  Regular Movement44_xgb  458        133  0.675882  0.462970
269          Residuals20_rf  458        133  0.702834  0.462852
270           Baseline21_en  458        133  0.650966  0.462768
271              Usage40_rf  458        133  0.647287  0.462349
272             No FIP23_en  458        133  0.685252  0.462213
273          Residuals19_rf  458        133  0.681272  0.462188
274   Regular Movement47_rf  458        133  0.687704  0.461565
275             Usage45_xgb  458        133  0.656750  0.461369
276   Regular Movement26_rf  458        133  0.678311  0.461159
277              Usage25_rf  458        133  0.657559  0.461082
278        Velo + FIP26_xgb  458        133  0.663852  0.461078
279              Usage3_xgb  458        133  0.640301  0.460684
280         Velo + FIP36_rf  458        133  0.673198  0.460407
281              Usage44_rf  458        133  0.649763  0.460083
282             No FIP6_xgb  458        133  0.704916  0.459543
283             No FIP5_xgb  458        133  0.684326  0.459044
284             Usage12_xgb  458        133  0.651822  0.458036
285           Residuals1_rf  458        133  0.675766  0.457675
286              Usage43_rf  458        133  0.651567  0.457673
287   Regular Movement1_xgb  458        133  0.683285  0.457479
288          Residuals23_en  458        133  0.646431  0.456915
289              Usage20_rf  458        133  0.643771  0.456767
290               Usage3_rf  458        133  0.658855  0.456443
291  Regular Movement26_xgb  458        133  0.668109  0.455109
292              Usage26_rf  458        133  0.654598  0.454584
293              Usage19_rf  458        133  0.657744  0.454289
294         Velo + FIP15_rf  458        133  0.670977  0.453893
295         Velo + FIP17_en  458        133  0.640000  0.453772
296          Residuals17_rf  458        133  0.666142  0.453274
297   Regular Movement44_rf  458        133  0.677663  0.453111
298              Usage23_rf  458        133  0.639722  0.452242
299            No FIP13_xgb  458        133  0.699364  0.452089
300           Residuals7_rf  458        133  0.664916  0.451671
301          Residuals43_rf  458        133  0.687172  0.451481
302        Velo + FIP45_xgb  458        133  0.661793  0.451230
303         Velo + FIP20_rf  458        133  0.656194  0.450940
304              Usage9_xgb  458        133  0.645529  0.450881
305         Velo + FIP3_xgb  458        133  0.650758  0.450642
306   Regular Movement22_en  458        133  0.641180  0.449089
307         Velo + FIP22_en  458        133  0.641180  0.449089
308          Residuals31_rf  458        133  0.678010  0.448688
309          Residuals24_en  458        133  0.669011  0.448539
310          Residuals25_en  458        133  0.665957  0.447439

In [17]:
two_year_breakout_df = helpy.is_breakout(base_analysis.results_df, .10, 100, 2)
base_analysis.get_model_metrics(df=two_year_breakout_df)

                      Model    N  Breakouts   ROC-AUC    PR-AUC
0                No FIP5_en  458        117  0.729754  0.516043
1                No FIP4_en  458        117  0.729704  0.515947
2               No FIP11_en  458        117  0.729980  0.515837
3                No FIP3_en  458        117  0.729729  0.515629
4                No FIP2_en  458        117  0.729629  0.514946
5                No FIP1_en  458        117  0.729579  0.514663
6                No FIP0_en  458        117  0.729478  0.514482
7               No FIP10_en  458        117  0.729879  0.513325
8                No FIP9_en  458        117  0.729754  0.511191
9                No FIP8_en  458        117  0.728501  0.505684
10               No FIP7_en  458        117  0.728125  0.502867
11               No FIP6_en  458        117  0.727749  0.502648
12              No FIP17_en  458        117  0.724290  0.499922
13           Residuals29_rf  458        117  0.717999  0.496330
14           Residuals27_rf  458        117  0.729428  0.495974
15              No FIP41_rf  458        117  0.726496  0.493503
16              No FIP16_en  458        117  0.719904  0.491467
17           Residuals25_rf  458        117  0.710454  0.490076
18              No FIP12_rf  458        117  0.718174  0.490045
19              No FIP46_rf  458        117  0.725293  0.489208
20              No FIP27_rf  458        117  0.726245  0.488670
21              No FIP24_rf  458        117  0.724365  0.487159
22           Residuals30_rf  458        117  0.727649  0.486217
23           Residuals41_rf  458        117  0.716269  0.486154
24              No FIP36_rf  458        117  0.724240  0.485208
25              No FIP3_xgb  458        117  0.724491  0.484580
26              No FIP18_rf  458        117  0.725067  0.484572
27              No FIP30_rf  458        117  0.723739  0.484298
28             No FIP34_xgb  458        117  0.734316  0.483638
29             No FIP21_xgb  458        117  0.730230  0.483293
30           Residuals36_rf  458        117  0.717247  0.483291
31              No FIP15_en  458        117  0.715918  0.482499
32              No FIP29_rf  458        117  0.722335  0.482481
33             No FIP45_xgb  458        117  0.726045  0.481718
34             No FIP26_xgb  458        117  0.727448  0.480931
35              No FIP7_xgb  458        117  0.721007  0.480166
36             No FIP19_xgb  458        117  0.733865  0.479076
37           Residuals18_rf  458        117  0.717322  0.477520
38               No FIP5_rf  458        117  0.721207  0.476406
39             No FIP48_xgb  458        117  0.725644  0.476319
40             No FIP22_xgb  458        117  0.716746  0.476248
41                Usage5_rf  458        117  0.692258  0.475766
42             No FIP12_xgb  458        117  0.713186  0.474905
43              No FIP47_rf  458        117  0.722711  0.474865
44              No FIP43_rf  458        117  0.720380  0.474800
45              No FIP13_rf  458        117  0.716620  0.474500
46             No FIP29_xgb  458        117  0.729654  0.474454
47              No FIP15_rf  458        117  0.719703  0.473375
48               No FIP1_rf  458        117  0.714314  0.472519
49              No FIP11_rf  458        117  0.724942  0.472513
50               Usage46_rf  458        117  0.696268  0.472327
51            Residuals5_rf  458        117  0.723563  0.471600
52    Regular Movement41_rf  458        117  0.702509  0.471374
53             No FIP35_xgb  458        117  0.717949  0.471320
54              No FIP38_rf  458        117  0.714465  0.470937
55               Usage11_rf  458        117  0.681455  0.470330
56              No FIP9_xgb  458        117  0.707021  0.470030
57             No FIP47_xgb  458        117  0.720681  0.470009
58          Residuals21_xgb  458        117  0.719402  0.470007
59              No FIP14_en  458        117  0.712635  0.469691
60              No FIP19_rf  458        117  0.716370  0.469650
61              No FIP48_rf  458        117  0.715217  0.469627
62              No FIP14_rf  458        117  0.714816  0.468880
63              No FIP40_rf  458        117  0.716996  0.468573
64           Residuals24_rf  458        117  0.723789  0.468140
65             No FIP40_xgb  458        117  0.731459  0.467746
66             No FIP39_xgb  458        117  0.721408  0.467630
67              No FIP13_en  458        117  0.711482  0.467487
68              No FIP44_rf  458        117  0.717723  0.467036
69             No FIP15_xgb  458        117  0.728576  0.466404
70             No FIP27_xgb  458        117  0.704865  0.465891
71              No FIP26_rf  458        117  0.715668  0.465008
72              No FIP1_xgb  458        117  0.712184  0.464340
73             No FIP44_xgb  458        117  0.722611  0.463425
74              No FIP12_en  458        117  0.710505  0.463322
75               Usage36_rf  458        117  0.674587  0.462697
76              No FIP25_rf  458        117  0.719453  0.462535
77              No FIP32_rf  458        117  0.713036  0.462430
78    Regular Movement11_rf  458        117  0.699677  0.461879
79              No FIP37_rf  458        117  0.694589  0.461541
80             No FIP49_xgb  458        117  0.723237  0.461023
81              No FIP31_rf  458        117  0.713663  0.461002
82              No FIP2_xgb  458        117  0.710605  0.460663
83               No FIP3_rf  458        117  0.713036  0.460615
84           Residuals46_rf  458        117  0.719277  0.460467
85    Regular Movement46_rf  458        117  0.708600  0.460146
86              No FIP20_rf  458        117  0.710530  0.459589
87           Residuals11_rf  458        117  0.717372  0.459562
88               Usage18_rf  458        117  0.670802  0.459485
89             No FIP36_xgb  458        117  0.720004  0.458240
90           Residuals48_rf  458        117  0.704940  0.458062
91             No FIP30_xgb  458        117  0.728952  0.457807
92              No FIP34_rf  458        117  0.702409  0.456788
93          Residuals12_xgb  458        117  0.694463  0.456756
94              No FIP23_rf  458        117  0.711507  0.456126
95           Residuals47_rf  458        117  0.705993  0.455902
96               No FIP8_rf  458        117  0.714891  0.455324
97             No FIP31_xgb  458        117  0.703461  0.455214
98             No FIP10_xgb  458        117  0.700303  0.455092
99    Regular Movement24_rf  458        117  0.711632  0.455068
100             No FIP39_rf  458        117  0.707321  0.454086
101             No FIP8_xgb  458        117  0.704614  0.453999
102   Regular Movement36_rf  458        117  0.705567  0.453579
103            No FIP32_xgb  458        117  0.711081  0.453027
104              Usage29_rf  458        117  0.671228  0.452952
105              Usage48_rf  458        117  0.662857  0.452371
106   Regular Movement30_rf  458        117  0.707096  0.452243
107              Usage27_rf  458        117  0.688373  0.452111
108          Residuals15_rf  458        117  0.704063  0.451923
109            No FIP16_xgb  458        117  0.713437  0.451460
110          Residuals7_xgb  458        117  0.714189  0.451454
111            No FIP14_xgb  458        117  0.708700  0.451258
112             No FIP45_rf  458        117  0.706093  0.451076
113              Usage41_rf  458        117  0.674061  0.450674
114              Usage30_rf  458        117  0.684036  0.450552
115             No FIP35_rf  458        117  0.695767  0.450257
116              No FIP4_rf  458        117  0.697421  0.450257
117             No FIP17_rf  458        117  0.707346  0.450085
118              Usage47_rf  458        117  0.664887  0.449727
119             No FIP49_rf  458        117  0.701130  0.449655
120             No FIP16_rf  458        117  0.699952  0.449329
121            No FIP17_xgb  458        117  0.726897  0.449175
122              No FIP6_rf  458        117  0.695015  0.448328
123            No FIP18_xgb  458        117  0.710254  0.447727
124    Regular Movement5_rf  458        117  0.707948  0.447659
125              Usage15_rf  458        117  0.672406  0.447237
126   Regular Movement27_rf  458        117  0.708073  0.446644
127             No FIP22_rf  458        117  0.690879  0.446197
128              No FIP2_rf  458        117  0.698098  0.446058
129          Residuals14_rf  458        117  0.701732  0.445871
130          Residuals44_rf  458        117  0.706093  0.445802
131         Velo + FIP23_rf  458        117  0.657293  0.445790
132              No FIP7_rf  458        117  0.702108  0.445291
133          Residuals32_rf  458        117  0.687019  0.445146
134              No FIP9_rf  458        117  0.685816  0.443791
135             No FIP33_rf  458        117  0.688147  0.442867
136   Regular Movement29_rf  458        117  0.702484  0.442820
137            No FIP20_xgb  458        117  0.708875  0.442787
138         Velo + FIP27_rf  458        117  0.689250  0.442680
139          Residuals40_rf  458        117  0.706269  0.442517
140   Regular Movement13_rf  458        117  0.694012  0.442513
141         Velo + FIP30_rf  458        117  0.688297  0.441464
142              Usage24_rf  458        117  0.688648  0.441323
143   Regular Movement7_xgb  458        117  0.704740  0.440978
144             No FIP42_rf  458        117  0.689701  0.440454
145             No FIP28_rf  458        117  0.687069  0.440323
146          Residuals19_rf  458        117  0.686242  0.439949
147             No FIP10_rf  458        117  0.690303  0.439604
148            No FIP33_xgb  458        117  0.713287  0.438735
149   Regular Movement18_rf  458        117  0.700629  0.437792
150         Velo + FIP41_rf  458        117  0.674938  0.437362
151          Residuals23_rf  458        117  0.694037  0.437335
152         Residuals14_xgb  458        117  0.702559  0.436192
153          Residuals8_xgb  458        117  0.690277  0.436125
154         Velo + FIP18_en  458        117  0.662531  0.436029
155              No FIP0_rf  458        117  0.689801  0.435865
156         Velo + FIP25_rf  458        117  0.670602  0.435317
157              Usage12_rf  458        117  0.664912  0.434651
158            No FIP37_xgb  458        117  0.705492  0.434461
159          Residuals1_xgb  458        117  0.689425  0.434106
160             No FIP21_rf  458        117  0.686317  0.433972
161         Velo + FIP18_rf  458        117  0.674913  0.433953
162   Regular Movement25_rf  458        117  0.698449  0.433362
163         Velo + FIP11_rf  458        117  0.675815  0.433262
164            No FIP24_xgb  458        117  0.704940  0.432918
165               Usage3_rf  458        117  0.663383  0.432729
166              Usage13_rf  458        117  0.666993  0.432469
167         Residuals39_xgb  458        117  0.694764  0.431817
168    Regular Movement5_en  458        117  0.676868  0.431480
169              Usage14_rf  458        117  0.658320  0.431441
170            No FIP28_xgb  458        117  0.713813  0.431432
171    Regular Movement3_en  458        117  0.676517  0.431036
172    Regular Movement1_en  458        117  0.677645  0.431024
173          Velo + FIP5_rf  458        117  0.685741  0.430963
174    Regular Movement2_en  458        117  0.676768  0.430892
175              Usage19_rf  458        117  0.663684  0.430882
176              Usage43_rf  458        117  0.653483  0.430837
177           Residuals5_en  458        117  0.676893  0.430810
178    Regular Movement0_en  458        117  0.677469  0.430742
179    Regular Movement4_en  458        117  0.676492  0.430739
180              Usage7_xgb  458        117  0.683259  0.430696
181           Residuals1_en  458        117  0.677319  0.430666
182           Residuals2_en  458        117  0.677269  0.430584
183           Residuals3_en  458        117  0.677043  0.430573
184           Residuals4_en  458        117  0.676968  0.430148
185          Residuals13_rf  458        117  0.703662  0.429734
186           Residuals0_en  458        117  0.677319  0.429732
187          Residuals11_en  458        117  0.680327  0.429423
188              Usage25_rf  458        117  0.665764  0.429332
189   Regular Movement15_rf  458        117  0.690929  0.429238
190   Regular Movement47_rf  458        117  0.691932  0.428485
191         Velo + FIP13_rf  458        117  0.673685  0.428483
192          Residuals10_en  458        117  0.681029  0.428483
193             Usage44_xgb  458        117  0.683435  0.428290
194           Residuals7_en  458        117  0.682858  0.428277
195              Usage23_rf  458        117  0.640976  0.428272
196           Residuals6_en  458        117  0.683234  0.427951
197           Residuals9_en  458        117  0.681580  0.427890
198         Velo + FIP20_rf  458        117  0.660200  0.427690
199         Velo + FIP7_xgb  458        117  0.692007  0.427651
200           Residuals8_en  458        117  0.681806  0.427503
201   Regular Movement10_en  458        117  0.677018  0.427005
202            No FIP41_xgb  458        117  0.714239  0.426418
203         Velo + FIP46_rf  458        117  0.686317  0.426398
204         Residuals45_xgb  458        117  0.707196  0.426143
205    Regular Movement9_en  458        117  0.676266  0.425656
206           Residuals1_rf  458        117  0.680001  0.425489
207             No FIP0_gam  458        117  0.689626  0.425474
208    Regular Movement8_en  458        117  0.675890  0.425214
209             Usage14_xgb  458        117  0.679901  0.425134
210         Velo + FIP29_rf  458        117  0.670126  0.424916
211          Residuals18_en  458        117  0.691957  0.424874
212         Residuals34_xgb  458        117  0.697421  0.424559
213             Usage39_xgb  458        117  0.678071  0.424139
214   Regular Movement11_en  458        117  0.677495  0.423609
215          Residuals20_rf  458        117  0.703512  0.423591
216           Residuals8_rf  458        117  0.692207  0.423306
217              Usage20_rf  458        117  0.641778  0.423277
218         Velo + FIP19_en  458        117  0.657518  0.422770
219    Regular Movement7_en  458        117  0.674712  0.422346
220          Residuals43_rf  458        117  0.690277  0.422314
221             No FIP6_xgb  458        117  0.708625  0.421683
222          Residuals26_rf  458        117  0.696970  0.421668
223         Velo + FIP36_rf  458        117  0.669198  0.421541
224            No FIP23_xgb  458        117  0.710129  0.421206
225  Regular Movement21_xgb  458        117  0.699852  0.421133
226    Regular Movement6_en  458        117  0.673910  0.420980
227        Velo + FIP14_xgb  458        117  0.687195  0.420044
228          Residuals3_xgb  458        117  0.681530  0.419831
229           Baseline18_en  458        117  0.662531  0.419621
230             No FIP5_xgb  458        117  0.683184  0.419325
231             Usage34_xgb  458        117  0.631276  0.419020
232             No FIP18_en  458        117  0.688122  0.418718
233   Regular Movement18_en  458        117  0.666065  0.418634
234          Residuals12_rf  458        117  0.684864  0.418271
235              Usage20_en  458        117  0.657443  0.418000
236              Usage32_rf  458        117  0.650450  0.417101
237            No FIP13_xgb  458        117  0.700855  0.416631
238  Regular Movement14_xgb  458        117  0.693787  0.416319
239          Residuals19_en  458        117  0.686894  0.416314
240  Regular Movement39_xgb  458        117  0.681079  0.416043
241          Residuals17_en  458        117  0.679174  0.415601
242          Residuals31_rf  458        117  0.681705  0.415357
243   Regular Movement8_xgb  458        117  0.683284  0.415249
244        Velo + FIP44_xgb  458        117  0.686418  0.415052
245         Residuals26_xgb  458        117  0.689024  0.415042
246         Velo + FIP48_rf  458        117  0.664737  0.414773
247              Usage8_xgb  458        117  0.677745  0.413964
248   Regular Movement14_rf  458        117  0.689175  0.413877
249         Velo + FIP24_rf  458        117  0.681229  0.413610
250   Regular Movement19_en  458        117  0.661478  0.413475
251   Regular Movement32_rf  458        117  0.686042  0.412902
252  Regular Movement12_xgb  458        117  0.680377  0.412720
253             No FIP19_en  458        117  0.687545  0.412185
254          Velo + FIP3_rf  458        117  0.648771  0.411683
255        Velo + FIP39_xgb  458        117  0.675289  0.411623
256              Usage19_en  458        117  0.659974  0.411145
257   Regular Movement1_xgb  458        117  0.682106  0.409996
258          Residuals16_en  458        117  0.679876  0.409551
259             No FIP21_en  458        117  0.685014  0.409506
260             No FIP22_en  458        117  0.684337  0.409491
261         Velo + FIP8_xgb  458        117  0.682883  0.409337
262         Velo + FIP14_rf  458        117  0.668822  0.408885
263             Usage21_xgb  458        117  0.664160  0.408595
264              Usage18_en  458        117  0.662030  0.408061
265         Residuals44_xgb  458        117  0.687169  0.408023
266            No FIP42_xgb  458        117  0.678948  0.407885
267              Usage1_xgb  458        117  0.662982  0.407846
268           Residuals6_rf  458        117  0.641351  0.407694
269             No FIP23_en  458        117  0.683836  0.407469
270          Residuals20_en  458        117  0.679023  0.407392
271           Baseline19_en  458        117  0.658320  0.407339
272         Velo + FIP1_xgb  458        117  0.676241  0.407297
273         Velo + FIP47_rf  458        117  0.665138  0.407125
274             No FIP20_en  458        117  0.685590  0.406855
275   Regular Movement40_rf  458        117  0.682608  0.406144
276   Regular Movement20_rf  458        117  0.679149  0.406108
277         Velo + FIP15_rf  458        117  0.663684  0.405536
278   Regular Movement48_rf  458        117  0.688047  0.405500
279           Residuals3_rf  458        117  0.681354  0.404930
280            No FIP38_xgb  458        117  0.698398  0.404694
281             Usage26_xgb  458        117  0.659774  0.404622
282          Residuals12_en  458        117  0.685741  0.404257
283          Residuals15_en  458        117  0.680728  0.404017
284          Residuals13_en  458        117  0.684688  0.402956
285   Regular Movement12_rf  458        117  0.681354  0.402896
286         Velo + FIP43_rf  458        117  0.657744  0.402865
287   Regular Movement43_rf  458        117  0.679324  0.402011
288          Residuals14_en  458        117  0.681430  0.401858
289              Usage40_rf  458        117  0.644033  0.401784
290        Velo + FIP12_xgb  458        117  0.648545  0.400820
291   Regular Movement20_en  458        117  0.652154  0.400648
292              Usage9_xgb  458        117  0.638118  0.400609
293          Residuals39_rf  458        117  0.671103  0.400480
294              Usage21_en  458        117  0.646841  0.400426
295          Residuals9_xgb  458        117  0.661228  0.399379
296  Regular Movement44_xgb  458        117  0.675189  0.398677
297         Residuals22_xgb  458        117  0.667895  0.398538
298          Residuals21_en  458        117  0.664461  0.398272
299            No FIP11_xgb  458        117  0.687821  0.398219
300         Velo + FIP20_en  458        117  0.647367  0.398199
301         Residuals37_xgb  458        117  0.661754  0.398190
302              Usage3_xgb  458        117  0.630448  0.398120
303              Usage44_rf  458        117  0.648495  0.397470
304   Regular Movement26_rf  458        117  0.680302  0.397428
305           Baseline20_en  458        117  0.650625  0.397344
306    Regular Movement3_rf  458        117  0.677871  0.396916
307        Velo + FIP34_xgb  458        117  0.642404  0.396308
308          Residuals35_rf  458        117  0.640950  0.396111
309   Regular Movement44_rf  458        117  0.680778  0.394859
310         Residuals35_xgb  458        117  0.655413  0.393955

In [18]:
two_year_breakout_df = helpy.is_breakout(base_analysis.results_df, .20, 100, 2)
base_analysis.get_model_metrics(df=two_year_breakout_df)

                      Model    N  Breakouts   ROC-AUC    PR-AUC
0            Residuals27_rf  458         47  0.749858  0.288716
1            Residuals25_rf  458         47  0.707149  0.282420
2               No FIP27_rf  458         47  0.732567  0.279764
3               No FIP30_rf  458         47  0.728322  0.279252
4               No FIP24_rf  458         47  0.732878  0.278143
5            Residuals41_rf  458         47  0.723456  0.275791
6               No FIP12_rf  458         47  0.720557  0.274948
7            Residuals30_rf  458         47  0.746907  0.274354
8               No FIP13_rf  458         47  0.725786  0.273311
9                No FIP5_rf  458         47  0.727753  0.272117
10              No FIP29_rf  458         47  0.730496  0.271897
11              No FIP46_rf  458         47  0.730289  0.270040
12              No FIP48_rf  458         47  0.723663  0.269085
13            Residuals5_rf  458         47  0.742714  0.268941
14              No FIP18_rf  458         47  0.731014  0.268370
15              No FIP41_rf  458         47  0.730134  0.266983
16           Residuals29_rf  458         47  0.725786  0.265734
17              No FIP20_rf  458         47  0.717296  0.264903
18              No FIP14_rf  458         47  0.716571  0.263726
19              No FIP36_rf  458         47  0.727960  0.261276
20               No FIP3_rf  458         47  0.719263  0.261197
21              No FIP15_rf  458         47  0.725941  0.260541
22              No FIP43_rf  458         47  0.728995  0.259821
23              No FIP47_rf  458         47  0.723352  0.259721
24    Regular Movement41_rf  458         47  0.722369  0.258012
25              No FIP19_rf  458         47  0.733551  0.256371
26              No FIP32_rf  458         47  0.717865  0.256164
27              No FIP11_rf  458         47  0.732878  0.250529
28           Residuals24_rf  458         47  0.738883  0.250104
29              No FIP25_rf  458         47  0.710100  0.247834
30               Usage46_rf  458         47  0.709220  0.246058
31    Regular Movement27_rf  458         47  0.728736  0.245483
32           Residuals18_rf  458         47  0.732257  0.244926
33    Regular Movement36_rf  458         47  0.717554  0.243733
34              No FIP22_en  458         47  0.706269  0.241775
35              No FIP11_en  458         47  0.721955  0.241271
36              No FIP23_en  458         47  0.706166  0.240826
37             No FIP29_xgb  458         47  0.737175  0.240407
38     Regular Movement5_rf  458         47  0.724233  0.240055
39              No FIP17_en  458         47  0.724906  0.237828
40              No FIP1_xgb  458         47  0.713568  0.237430
41           Residuals14_rf  458         47  0.712171  0.236059
42                Usage5_rf  458         47  0.722162  0.235834
43              No FIP21_en  458         47  0.706890  0.234388
44              No FIP7_xgb  458         47  0.728736  0.234156
45              No FIP23_rf  458         47  0.709168  0.233916
46               No FIP5_en  458         47  0.719315  0.233796
47           Residuals23_rf  458         47  0.710203  0.233792
48               No FIP4_en  458         47  0.719159  0.233503
49               No FIP3_en  458         47  0.719004  0.233313
50               No FIP1_en  458         47  0.718538  0.233152
51              No FIP10_en  458         47  0.721282  0.232949
52             No FIP36_xgb  458         47  0.727494  0.232912
53               No FIP9_en  458         47  0.720816  0.232875
54               No FIP2_en  458         47  0.718486  0.232794
55               No FIP0_en  458         47  0.718590  0.232253
56           Residuals36_rf  458         47  0.719263  0.231599
57           Residuals47_rf  458         47  0.709427  0.231131
58               Usage25_rf  458         47  0.699746  0.230956
59              No FIP20_en  458         47  0.707356  0.230465
60               No FIP6_en  458         47  0.718952  0.230177
61               No FIP7_en  458         47  0.719677  0.229764
62               No FIP8_en  458         47  0.719263  0.229491
63               No FIP1_rf  458         47  0.716416  0.227735
64           Residuals15_rf  458         47  0.718227  0.227494
65              No FIP34_rf  458         47  0.704768  0.225985
66               Usage24_rf  458         47  0.710359  0.225956
67    Regular Movement29_rf  458         47  0.707046  0.225562
68           Residuals20_rf  458         47  0.719056  0.225374
69              No FIP19_en  458         47  0.706114  0.225332
70              No FIP16_en  458         47  0.721541  0.225207
71               Usage11_rf  458         47  0.721799  0.224402
72              No FIP12_en  458         47  0.715121  0.224219
73              No FIP14_en  458         47  0.715380  0.223997
74             No FIP48_xgb  458         47  0.720143  0.223570
75           Residuals43_rf  458         47  0.700678  0.223566
76             No FIP16_xgb  458         47  0.723301  0.223547
77              No FIP13_en  458         47  0.715277  0.223433
78           Residuals32_rf  458         47  0.697831  0.222880
79              No FIP15_en  458         47  0.718745  0.222482
80              No FIP44_rf  458         47  0.723922  0.222377
81           Residuals48_rf  458         47  0.709427  0.221990
82    Regular Movement24_rf  458         47  0.720764  0.221931
83               Usage13_rf  458         47  0.699798  0.221926
84             No FIP22_xgb  458         47  0.726459  0.221803
85           Residuals46_rf  458         47  0.732671  0.221145
86    Regular Movement46_rf  458         47  0.729150  0.220289
87               Usage18_rf  458         47  0.704716  0.219957
88             No FIP45_xgb  458         47  0.723404  0.219517
89           Residuals19_rf  458         47  0.693638  0.219309
90               Usage29_rf  458         47  0.705285  0.219277
91          Residuals21_xgb  458         47  0.718435  0.219200
92              No FIP18_en  458         47  0.705596  0.218981
93               Usage27_rf  458         47  0.716364  0.218831
94             No FIP17_xgb  458         47  0.744733  0.218577
95             No FIP49_xgb  458         47  0.729616  0.218539
96              No FIP38_rf  458         47  0.720712  0.218435
97             No FIP35_xgb  458         47  0.716830  0.218197
98             No FIP19_xgb  458         47  0.734948  0.217753
99               Usage36_rf  458         47  0.705751  0.217631
100             No FIP26_rf  458         47  0.716933  0.217495
101            No FIP21_xgb  458         47  0.735725  0.216899
102   Regular Movement30_rf  458         47  0.725371  0.216449
103   Regular Movement11_rf  458         47  0.692188  0.216088
104              Usage43_rf  458         47  0.685200  0.216043
105   Regular Movement13_rf  458         47  0.723301  0.215899
106             No FIP9_xgb  458         47  0.703991  0.215542
107              Usage41_rf  458         47  0.700471  0.215497
108         Velo + FIP27_rf  458         47  0.701921  0.215449
109             No FIP3_xgb  458         47  0.726666  0.215244
110              Usage32_rf  458         47  0.667340  0.215033
111            No FIP32_xgb  458         47  0.706839  0.214924
112            No FIP39_xgb  458         47  0.727183  0.214914
113           Residuals3_rf  458         47  0.687477  0.214376
114             No FIP39_rf  458         47  0.707926  0.214067
115          Residuals8_xgb  458         47  0.703940  0.214059
116   Regular Movement7_xgb  458         47  0.704354  0.214038
117              Usage15_rf  458         47  0.699953  0.214019
118   Regular Movement18_rf  458         47  0.700368  0.213985
119              No FIP8_rf  458         47  0.716260  0.213467
120              No FIP2_rf  458         47  0.693638  0.213280
121             No FIP8_xgb  458         47  0.711446  0.212972
122             No FIP16_rf  458         47  0.697831  0.212950
123            No FIP30_xgb  458         47  0.742144  0.212779
124            No FIP40_xgb  458         47  0.736450  0.212711
125          Residuals11_rf  458         47  0.707770  0.212639
126          Residuals13_rf  458         47  0.694207  0.211953
127              Usage30_rf  458         47  0.704923  0.211308
128             No FIP45_rf  458         47  0.708288  0.211186
129             No FIP33_rf  458         47  0.678936  0.210403
130              Usage47_rf  458         47  0.693534  0.210318
131          Residuals7_xgb  458         47  0.724595  0.210037
132            No FIP27_xgb  458         47  0.706062  0.209615
133             No FIP31_rf  458         47  0.707201  0.209592
134            No FIP34_xgb  458         47  0.734897  0.209278
135             No FIP40_rf  458         47  0.720402  0.207510
136          Residuals1_xgb  458         47  0.697313  0.206708
137         Velo + FIP24_rf  458         47  0.690842  0.206213
138            No FIP12_xgb  458         47  0.718383  0.206043
139            No FIP26_xgb  458         47  0.721385  0.205942
140               Usage3_rf  458         47  0.682766  0.205336
141            No FIP18_xgb  458         47  0.717192  0.205318
142         Residuals14_xgb  458         47  0.716726  0.204458
143            No FIP23_xgb  458         47  0.711912  0.203815
144             No FIP24_en  458         47  0.691826  0.203264
145              Usage48_rf  458         47  0.681731  0.203201
146   Regular Movement8_xgb  458         47  0.690894  0.202925
147            No FIP20_xgb  458         47  0.718745  0.202787
148            No FIP15_xgb  458         47  0.729513  0.202508
149            No FIP14_xgb  458         47  0.712326  0.202029
150            No FIP44_xgb  458         47  0.717399  0.201906
151         Velo + FIP25_rf  458         47  0.677279  0.201417
152            No FIP47_xgb  458         47  0.720143  0.201267
153              Usage8_xgb  458         47  0.700626  0.201221
154            No FIP31_xgb  458         47  0.711756  0.201108
155              Usage20_rf  458         47  0.656210  0.200211
156             No FIP5_xgb  458         47  0.690739  0.200038
157             No FIP6_xgb  458         47  0.719573  0.199786
158         Velo + FIP29_rf  458         47  0.673862  0.199475
159          Residuals44_rf  458         47  0.708340  0.199128
160              Usage7_xgb  458         47  0.702335  0.198659
161   Regular Movement1_xgb  458         47  0.672102  0.198316
162         Residuals39_xgb  458         47  0.715536  0.198289
163             No FIP25_en  458         47  0.687426  0.198267
164  Regular Movement35_xgb  458         47  0.654864  0.198115
165         Velo + FIP46_rf  458         47  0.690325  0.198041
166         Velo + FIP30_rf  458         47  0.695760  0.197679
167         Residuals12_xgb  458         47  0.691049  0.197488
168   Regular Movement47_rf  458         47  0.700160  0.197132
169             No FIP28_en  458         47  0.686649  0.197041
170             No FIP31_en  458         47  0.686649  0.197041
171             No FIP33_en  458         47  0.686649  0.197041
172   Regular Movement35_en  458         47  0.686649  0.197041
173         Velo + FIP29_en  458         47  0.686649  0.197041
174         Velo + FIP28_en  458         47  0.686649  0.197041
175             No FIP26_en  458         47  0.686649  0.197041
176         Velo + FIP31_en  458         47  0.686649  0.197041
177         Velo + FIP30_en  458         47  0.686649  0.197041
178          Residuals29_en  458         47  0.686649  0.197041
179   Regular Movement34_en  458         47  0.686649  0.197041
180   Regular Movement32_en  458         47  0.686649  0.197041
181   Regular Movement33_en  458         47  0.686649  0.197041
182   Regular Movement30_en  458         47  0.686649  0.197041
183         Velo + FIP32_en  458         47  0.686649  0.197041
184           Baseline34_en  458         47  0.686649  0.197041
185           Baseline32_en  458         47  0.686649  0.197041
186         Velo + FIP35_en  458         47  0.686649  0.197041
187         Velo + FIP34_en  458         47  0.686649  0.197041
188           Baseline33_en  458         47  0.686649  0.197041
189           Baseline31_en  458         47  0.686649  0.197041
190           Baseline30_en  458         47  0.686649  0.197041
191           Baseline28_en  458         47  0.686649  0.197041
192          Residuals31_en  458         47  0.686649  0.197041
193          Residuals32_en  458         47  0.686649  0.197041
194          Residuals33_en  458         47  0.686649  0.197041
195             No FIP32_en  458         47  0.686649  0.197041
196   Regular Movement28_en  458         47  0.686649  0.197041
197   Regular Movement29_en  458         47  0.686649  0.197041
198             No FIP27_en  458         47  0.686649  0.197041
199             No FIP29_en  458         47  0.686649  0.197041
200   Regular Movement31_en  458         47  0.686649  0.197041
201              Usage28_en  458         47  0.686649  0.197041
202              Usage33_en  458         47  0.686649  0.197041
203              Usage35_en  458         47  0.686649  0.197041
204              Usage32_en  458         47  0.686649  0.197041
205             No FIP35_en  458         47  0.686649  0.197041
206              Usage30_en  458         47  0.686649  0.197041
207              Usage31_en  458         47  0.686649  0.197041
208             No FIP34_en  458         47  0.686649  0.197041
209          Residuals28_en  458         47  0.686649  0.197041
210          Residuals35_en  458         47  0.686649  0.197041
211          Residuals30_en  458         47  0.686649  0.197041
212          Residuals34_en  458         47  0.686649  0.197041
213              Usage29_en  458         47  0.686649  0.197041
214             No FIP30_en  458         47  0.686649  0.197041
215              Usage34_en  458         47  0.686649  0.197041
216         Velo + FIP33_en  458         47  0.686649  0.197041
217           Baseline29_en  458         47  0.686649  0.197041
218           Baseline35_en  458         47  0.686649  0.197041
219             No FIP49_rf  458         47  0.704043  0.196937
220          Residuals27_en  458         47  0.686235  0.196105
221         Velo + FIP27_en  458         47  0.686235  0.196105
222              Usage27_en  458         47  0.686235  0.196105
223           Baseline27_en  458         47  0.686235  0.196105
224   Regular Movement27_en  458         47  0.686235  0.196105
225         Velo + FIP7_xgb  458         47  0.685044  0.196075
226             Usage14_xgb  458         47  0.690118  0.195975
227            No FIP38_xgb  458         47  0.704768  0.195606
228        Velo + FIP35_xgb  458         47  0.638143  0.195548
229         Velo + FIP18_rf  458         47  0.678884  0.195425
230          Residuals12_rf  458         47  0.692965  0.194761
231          Residuals24_en  458         47  0.686494  0.194457
232  Regular Movement14_xgb  458         47  0.703888  0.194376
233   Regular Movement14_rf  458         47  0.698556  0.194148
234            No FIP41_xgb  458         47  0.712533  0.194113
235        Velo + FIP14_xgb  458         47  0.689289  0.193980
236             Usage44_xgb  458         47  0.705234  0.193920
237          Residuals25_en  458         47  0.684009  0.193730
238              Usage12_rf  458         47  0.694000  0.193452
239         Velo + FIP8_xgb  458         47  0.684734  0.193310
240          Residuals3_xgb  458         47  0.694880  0.193207
241              Usage19_rf  458         47  0.693275  0.193121
242              Usage1_xgb  458         47  0.694362  0.193017
243         Velo + FIP26_en  458         47  0.683854  0.192807
244   Regular Movement26_en  458         47  0.683854  0.192807
245           Baseline26_en  458         47  0.683854  0.192807
246              Usage26_en  458         47  0.683854  0.192807
247          Residuals26_en  458         47  0.683854  0.192807
248   Regular Movement25_rf  458         47  0.700368  0.192801
249         Velo + FIP41_rf  458         47  0.673759  0.192745
250           Baseline27_rf  458         47  0.686597  0.192560
251           Baseline46_rf  458         47  0.696692  0.192520
252              No FIP9_rf  458         47  0.687270  0.192159
253         Residuals38_xgb  458         47  0.670601  0.191806
254          Residuals40_rf  458         47  0.703370  0.191775
255              Usage25_en  458         47  0.682818  0.191772
256           Baseline25_en  458         47  0.682818  0.191772
257   Regular Movement25_en  458         47  0.682818  0.191772
258         Velo + FIP25_en  458         47  0.682818  0.191772
259         Residuals45_xgb  458         47  0.700109  0.191511
260         Residuals34_xgb  458         47  0.686338  0.191048
261           Baseline24_en  458         47  0.682197  0.190834
262        Velo + FIP44_xgb  458         47  0.696071  0.190588
263          Velo + FIP5_rf  458         47  0.692913  0.190189
264           Baseline30_rf  458         47  0.698142  0.190069
265   Regular Movement23_rf  458         47  0.683957  0.189946
266              Usage24_en  458         47  0.684061  0.189742
267   Regular Movement32_rf  458         47  0.699850  0.189674
268            No FIP28_xgb  458         47  0.718279  0.189394
269          Residuals26_rf  458         47  0.697572  0.188681
270              Usage14_rf  458         47  0.681213  0.188639
271              Usage23_rf  458         47  0.655951  0.188346
272   Regular Movement24_en  458         47  0.681524  0.188250
273         Velo + FIP23_rf  458         47  0.631309  0.188245
274            No FIP37_xgb  458         47  0.705907  0.187860
275              No FIP4_rf  458         47  0.699022  0.187801
276         Velo + FIP24_en  458         47  0.681006  0.187595
277         Velo + FIP11_rf  458         47  0.673241  0.187491
278          Baseline44_xgb  458         47  0.667857  0.187416
279             No FIP22_rf  458         47  0.690946  0.187383
280              No FIP0_rf  458         47  0.693534  0.187074
281             Usage39_xgb  458         47  0.696071  0.186935
282         Velo + FIP36_rf  458         47  0.671947  0.186767
283   Regular Movement15_rf  458         47  0.695398  0.186691
284              No FIP7_rf  458         47  0.709582  0.186675
285            No FIP10_xgb  458         47  0.700212  0.186481
286  Regular Movement39_xgb  458         47  0.694311  0.186432
287             No FIP2_xgb  458         47  0.701558  0.186124
288             No FIP17_rf  458         47  0.706114  0.185932
289           Baseline24_rf  458         47  0.688979  0.185692
290             No FIP0_gam  458         47  0.685200  0.185300
291        Velo + FIP31_xgb  458         47  0.595796  0.185221
292            No FIP46_xgb  458         47  0.698400  0.185060
293              No FIP6_rf  458         47  0.695087  0.184898
294   Regular Movement48_rf  458         47  0.692706  0.184487
295         Residuals44_xgb  458         47  0.696744  0.184400
296           Baseline8_xgb  458         47  0.674277  0.184387
297            No FIP11_xgb  458         47  0.687943  0.184070
298              Usage9_xgb  458         47  0.662163  0.183925
299             No FIP21_rf  458         47  0.689600  0.183891
300             No FIP10_rf  458         47  0.687270  0.183531
301           Residuals8_rf  458         47  0.694725  0.182396
302         Residuals24_xgb  458         47  0.647513  0.182041
303            Baseline5_rf  458         47  0.682197  0.181947
304  Regular Movement21_xgb  458         47  0.690842  0.181494
305        Velo + FIP39_xgb  458         47  0.684475  0.181489
306   Regular Movement3_xgb  458         47  0.662266  0.181449
307         Residuals26_xgb  458         47  0.693120  0.181251
308            No FIP24_xgb  458         47  0.695346  0.181073
309   Regular Movement20_rf  458         47  0.681162  0.180852
310            No FIP43_xgb  458         47  0.690169  0.180567

In [19]:
two_year_breakout_df = helpy.is_breakout(base_analysis.results_df, .10, 110, 2)
base_analysis.get_model_metrics(df=two_year_breakout_df)

                      Model    N  Breakouts   ROC-AUC    PR-AUC
0               No FIP11_en  458        130  0.754315  0.577745
1                No FIP9_en  458        130  0.755324  0.576736
2               No FIP10_en  458        130  0.754855  0.576469
3                No FIP0_en  458        130  0.753518  0.575833
4                No FIP1_en  458        130  0.753447  0.575789
5                No FIP4_en  458        130  0.753189  0.575622
6                No FIP5_en  458        130  0.753096  0.575520
7                No FIP3_en  458        130  0.753283  0.575398
8                No FIP2_en  458        130  0.753283  0.575281
9                No FIP8_en  458        130  0.754972  0.573530
10               No FIP7_en  458        130  0.754972  0.572838
11               No FIP6_en  458        130  0.754784  0.572760
12              No FIP17_en  458        130  0.753189  0.571506
13              No FIP7_xgb  458        130  0.743269  0.566166
14              No FIP16_en  458        130  0.750117  0.564714
15           Residuals27_rf  458        130  0.747819  0.563580
16              No FIP8_xgb  458        130  0.735061  0.560520
17           Residuals30_rf  458        130  0.745098  0.556499
18              No FIP15_en  458        130  0.746811  0.556175
19              No FIP3_xgb  458        130  0.740572  0.554062
20             No FIP21_xgb  458        130  0.746904  0.553984
21                Usage5_rf  458        130  0.713508  0.553365
22              No FIP30_rf  458        130  0.746670  0.551916
23              No FIP24_rf  458        130  0.746459  0.551861
24             No FIP19_xgb  458        130  0.747326  0.551749
25             No FIP39_xgb  458        130  0.745966  0.551608
26             No FIP12_xgb  458        130  0.734475  0.550672
27             No FIP34_xgb  458        130  0.747538  0.550322
28              No FIP27_rf  458        130  0.747350  0.550277
29              No FIP41_rf  458        130  0.741909  0.550045
30           Residuals29_rf  458        130  0.724414  0.549220
31            Residuals5_rf  458        130  0.742237  0.548820
32           Residuals36_rf  458        130  0.724719  0.546675
33             No FIP26_xgb  458        130  0.746177  0.546261
34             No FIP14_xgb  458        130  0.737852  0.544971
35              No FIP46_rf  458        130  0.745872  0.544820
36           Residuals24_rf  458        130  0.744348  0.544702
37               Usage46_rf  458        130  0.717472  0.544165
38           Residuals41_rf  458        130  0.724883  0.544160
39               Usage27_rf  458        130  0.710741  0.544104
40              No FIP14_en  458        130  0.744184  0.544094
41             No FIP45_xgb  458        130  0.742214  0.543924
42              No FIP18_rf  458        130  0.741698  0.542986
43              No FIP11_rf  458        130  0.745568  0.542856
44              No FIP29_rf  458        130  0.739118  0.542811
45              No FIP13_en  458        130  0.743269  0.541806
46               Usage11_rf  458        130  0.698992  0.541113
47           Residuals8_xgb  458        130  0.726431  0.540518
48               No FIP5_rf  458        130  0.743668  0.540130
49             No FIP44_xgb  458        130  0.745755  0.539527
50              No FIP12_rf  458        130  0.735061  0.539182
51              No FIP36_rf  458        130  0.740619  0.538837
52    Regular Movement24_rf  458        130  0.733255  0.538536
53              No FIP12_en  458        130  0.742425  0.538005
54           Residuals46_rf  458        130  0.735084  0.537439
55           Residuals18_rf  458        130  0.724390  0.537180
56              No FIP31_rf  458        130  0.728870  0.537005
57           Residuals7_xgb  458        130  0.735084  0.536387
58               Usage18_rf  458        130  0.682645  0.534678
59               Usage30_rf  458        130  0.705699  0.534651
60               Usage36_rf  458        130  0.687430  0.534633
61              No FIP47_rf  458        130  0.738907  0.533838
62          Residuals12_xgb  458        130  0.710530  0.533779
63             No FIP29_xgb  458        130  0.742566  0.533598
64              No FIP9_xgb  458        130  0.718973  0.532843
65              No FIP43_rf  458        130  0.735999  0.532637
66    Regular Movement30_rf  458        130  0.727556  0.532539
67    Regular Movement7_xgb  458        130  0.724836  0.532366
68              No FIP1_xgb  458        130  0.732810  0.531928
69             No FIP22_xgb  458        130  0.727556  0.531259
70              No FIP40_rf  458        130  0.735647  0.531230
71               No FIP1_rf  458        130  0.728917  0.531104
72             No FIP15_xgb  458        130  0.741370  0.530992
73             No FIP47_xgb  458        130  0.735178  0.530976
74    Regular Movement41_rf  458        130  0.712430  0.530305
75              No FIP38_rf  458        130  0.727861  0.530203
76              Usage14_xgb  458        130  0.708419  0.529894
77              No FIP44_rf  458        130  0.735929  0.529720
78              No FIP15_rf  458        130  0.737195  0.529446
79             No FIP27_xgb  458        130  0.715666  0.529395
80             No FIP35_xgb  458        130  0.725258  0.529382
81               Usage24_rf  458        130  0.711327  0.529272
82    Regular Movement46_rf  458        130  0.723100  0.529079
83          Residuals14_xgb  458        130  0.732505  0.528782
84               Usage29_rf  458        130  0.685155  0.528737
85          Residuals21_xgb  458        130  0.722795  0.528702
86              No FIP26_rf  458        130  0.735014  0.528368
87              No FIP13_rf  458        130  0.733583  0.528357
88    Regular Movement11_rf  458        130  0.712500  0.527276
89             No FIP48_xgb  458        130  0.733161  0.526851
90    Regular Movement27_rf  458        130  0.729948  0.526574
91    Regular Movement8_xgb  458        130  0.719465  0.526511
92           Residuals25_rf  458        130  0.712828  0.525629
93               Usage41_rf  458        130  0.685413  0.525612
94              No FIP48_rf  458        130  0.731801  0.525419
95              Usage44_xgb  458        130  0.707856  0.525007
96               Usage8_xgb  458        130  0.713086  0.523985
97              No FIP18_en  458        130  0.727791  0.523381
98     Regular Movement5_rf  458        130  0.729362  0.522939
99             No FIP40_xgb  458        130  0.737195  0.522889
100            No FIP30_xgb  458        130  0.735835  0.522464
101              Usage47_rf  458        130  0.674859  0.521242
102         Velo + FIP8_xgb  458        130  0.719207  0.520824
103         Residuals39_xgb  458        130  0.714916  0.520560
104             No FIP37_rf  458        130  0.709498  0.520236
105              Usage7_xgb  458        130  0.708419  0.519911
106             Usage39_xgb  458        130  0.697256  0.519733
107             No FIP19_rf  458        130  0.731942  0.518943
108             No FIP14_rf  458        130  0.730347  0.518754
109             No FIP17_rf  458        130  0.726243  0.518356
110          Residuals40_rf  458        130  0.713368  0.518286
111             No FIP19_en  458        130  0.727369  0.517761
112              No FIP8_rf  458        130  0.733701  0.517358
113        Velo + FIP14_xgb  458        130  0.719020  0.517105
114             No FIP23_rf  458        130  0.729409  0.516966
115          Residuals44_rf  458        130  0.711351  0.516819
116            No FIP49_xgb  458        130  0.733466  0.516123
117             No FIP2_xgb  458        130  0.725704  0.515725
118             No FIP20_rf  458        130  0.726431  0.515435
119             No FIP32_rf  458        130  0.729081  0.513922
120         Velo + FIP7_xgb  458        130  0.716534  0.513786
121             No FIP49_rf  458        130  0.715760  0.513121
122             No FIP34_rf  458        130  0.717941  0.513046
123             No FIP39_rf  458        130  0.723687  0.512913
124              No FIP4_rf  458        130  0.712969  0.512835
125              No FIP3_rf  458        130  0.728330  0.512604
126            No FIP36_xgb  458        130  0.726806  0.511985
127             No FIP45_rf  458        130  0.723053  0.511613
128            No FIP32_xgb  458        130  0.720708  0.511516
129          Residuals48_rf  458        130  0.710952  0.511473
130         Velo + FIP30_rf  458        130  0.706731  0.511225
131              No FIP6_rf  458        130  0.711210  0.511063
132             No FIP24_en  458        130  0.713485  0.510991
133             No FIP25_rf  458        130  0.734287  0.510898
134          Residuals24_en  458        130  0.712453  0.510203
135              Usage12_rf  458        130  0.676407  0.510049
136             No FIP21_en  458        130  0.723499  0.509928
137              No FIP7_rf  458        130  0.720826  0.509735
138              Usage15_rf  458        130  0.685084  0.509732
139   Regular Movement29_rf  458        130  0.713508  0.509649
140              Usage25_rf  458        130  0.680582  0.509379
141   Regular Movement36_rf  458        130  0.714048  0.509168
142         Velo + FIP27_rf  458        130  0.709475  0.508770
143              Usage48_rf  458        130  0.672209  0.507922
144             No FIP20_en  458        130  0.725047  0.507602
145        Velo + FIP44_xgb  458        130  0.710342  0.507429
146            No FIP17_xgb  458        130  0.732247  0.507407
147             No FIP22_rf  458        130  0.708537  0.507015
148          Residuals47_rf  458        130  0.711538  0.506979
149  Regular Movement39_xgb  458        130  0.701313  0.506485
150          Residuals25_en  458        130  0.709475  0.506255
151           Baseline24_en  458        130  0.708654  0.505743
152  Regular Movement14_xgb  458        130  0.725070  0.505722
153             No FIP16_rf  458        130  0.714916  0.505681
154          Residuals11_rf  458        130  0.719934  0.505654
155              Usage25_en  458        130  0.708630  0.504949
156           Baseline25_en  458        130  0.708630  0.504949
157   Regular Movement25_en  458        130  0.708630  0.504949
158         Velo + FIP25_en  458        130  0.708630  0.504949
159              Usage13_rf  458        130  0.680066  0.504928
160          Velo + FIP5_rf  458        130  0.703776  0.504774
161             No FIP35_rf  458        130  0.710436  0.504773
162         Velo + FIP26_en  458        130  0.708748  0.504750
163   Regular Movement26_en  458        130  0.708748  0.504750
164           Baseline26_en  458        130  0.708748  0.504750
165              Usage26_en  458        130  0.708748  0.504750
166          Residuals26_en  458        130  0.708748  0.504750
167            No FIP31_xgb  458        130  0.710788  0.504628
168            No FIP18_xgb  458        130  0.717542  0.504508
169             No FIP25_en  458        130  0.709991  0.504358
170   Regular Movement18_rf  458        130  0.713649  0.504354
171              Usage24_en  458        130  0.709498  0.504237
172             No FIP33_en  458        130  0.709334  0.503907
173             No FIP34_en  458        130  0.709334  0.503907
174             No FIP27_en  458        130  0.709334  0.503907
175              Usage33_en  458        130  0.709334  0.503907
176             No FIP28_en  458        130  0.709334  0.503907
177             No FIP31_en  458        130  0.709334  0.503907
178             No FIP35_en  458        130  0.709334  0.503907
179              Usage31_en  458        130  0.709334  0.503907
180              Usage32_en  458        130  0.709334  0.503907
181             No FIP26_en  458        130  0.709334  0.503907
182              Usage29_en  458        130  0.709334  0.503907
183              Usage30_en  458        130  0.709334  0.503907
184          Residuals34_en  458        130  0.709334  0.503907
185          Residuals31_en  458        130  0.709334  0.503907
186         Velo + FIP34_en  458        130  0.709334  0.503907
187         Velo + FIP35_en  458        130  0.709334  0.503907
188          Residuals33_en  458        130  0.709334  0.503907
189          Residuals29_en  458        130  0.709334  0.503907
190         Velo + FIP28_en  458        130  0.709334  0.503907
191         Velo + FIP30_en  458        130  0.709334  0.503907
192          Residuals30_en  458        130  0.709334  0.503907
193         Velo + FIP29_en  458        130  0.709334  0.503907
194          Residuals32_en  458        130  0.709334  0.503907
195          Residuals35_en  458        130  0.709334  0.503907
196         Velo + FIP33_en  458        130  0.709334  0.503907
197         Velo + FIP32_en  458        130  0.709334  0.503907
198           Baseline35_en  458        130  0.709334  0.503907
199           Baseline34_en  458        130  0.709334  0.503907
200         Velo + FIP31_en  458        130  0.709334  0.503907
201          Residuals28_en  458        130  0.709334  0.503907
202   Regular Movement32_en  458        130  0.709334  0.503907
203   Regular Movement34_en  458        130  0.709334  0.503907
204   Regular Movement30_en  458        130  0.709334  0.503907
205   Regular Movement31_en  458        130  0.709334  0.503907
206   Regular Movement28_en  458        130  0.709334  0.503907
207   Regular Movement29_en  458        130  0.709334  0.503907
208   Regular Movement35_en  458        130  0.709334  0.503907
209   Regular Movement33_en  458        130  0.709334  0.503907
210           Baseline33_en  458        130  0.709334  0.503907
211           Baseline32_en  458        130  0.709334  0.503907
212           Baseline31_en  458        130  0.709334  0.503907
213           Baseline30_en  458        130  0.709334  0.503907
214              Usage35_en  458        130  0.709334  0.503907
215              Usage28_en  458        130  0.709334  0.503907
216              Usage34_en  458        130  0.709334  0.503907
217           Baseline28_en  458        130  0.709334  0.503907
218           Baseline29_en  458        130  0.709334  0.503907
219             No FIP32_en  458        130  0.709334  0.503907
220             No FIP29_en  458        130  0.709334  0.503907
221             No FIP30_en  458        130  0.709334  0.503907
222              Usage19_rf  458        130  0.675492  0.503825
223   Regular Movement27_en  458        130  0.709287  0.503614
224           Baseline27_en  458        130  0.709287  0.503614
225              Usage27_en  458        130  0.709287  0.503614
226          Residuals27_en  458        130  0.709287  0.503614
227         Velo + FIP27_en  458        130  0.709287  0.503614
228             No FIP22_en  458        130  0.722749  0.503588
229             No FIP42_rf  458        130  0.706473  0.503544
230              No FIP2_rf  458        130  0.714447  0.503301
231         Residuals44_xgb  458        130  0.712828  0.503110
232   Regular Movement24_en  458        130  0.708818  0.503062
233          Residuals1_xgb  458        130  0.710976  0.502810
234         Velo + FIP46_rf  458        130  0.705535  0.502680
235         Velo + FIP24_en  458        130  0.708560  0.502658
236              No FIP9_rf  458        130  0.702017  0.502179
237            No FIP33_xgb  458        130  0.727603  0.501938
238        Velo + FIP39_xgb  458        130  0.694794  0.501594
239            No FIP10_xgb  458        130  0.705230  0.500946
240            No FIP16_xgb  458        130  0.722655  0.500895
241               Usage3_rf  458        130  0.671834  0.500790
242             No FIP23_en  458        130  0.722068  0.500170
243   Regular Movement13_rf  458        130  0.702533  0.499876
244  Regular Movement12_xgb  458        130  0.701407  0.499859
245             No FIP28_rf  458        130  0.703659  0.499702
246             No FIP10_rf  458        130  0.707458  0.499420
247         Velo + FIP41_rf  458        130  0.686023  0.499366
248          Residuals15_rf  458        130  0.709756  0.498815
249   Regular Movement25_rf  458        130  0.707505  0.498134
250            No FIP37_xgb  458        130  0.722045  0.497884
251          Residuals14_rf  458        130  0.707880  0.497114
252            No FIP20_xgb  458        130  0.718035  0.496889
253         Velo + FIP18_rf  458        130  0.687172  0.496446
254              Usage43_rf  458        130  0.662219  0.494009
255              Usage14_rf  458        130  0.666487  0.493350
256             No FIP33_rf  458        130  0.703612  0.492356
257         Velo + FIP25_rf  458        130  0.683114  0.492230
258            No FIP24_xgb  458        130  0.716299  0.492056
259           Baseline8_xgb  458        130  0.706074  0.491806
260              Usage20_rf  458        130  0.653025  0.491350
261         Residuals45_xgb  458        130  0.709264  0.491093
262          Residuals26_rf  458        130  0.703635  0.490671
263  Regular Movement44_xgb  458        130  0.701477  0.490327
264              No FIP0_rf  458        130  0.707411  0.489909
265         Velo + FIP24_rf  458        130  0.700704  0.489490
266         Residuals26_xgb  458        130  0.704057  0.489419
267             No FIP21_rf  458        130  0.703870  0.488866
268         Velo + FIP11_rf  458        130  0.690502  0.488750
269         Velo + FIP1_xgb  458        130  0.701618  0.488214
270             Usage26_xgb  458        130  0.670521  0.487177
271             Usage12_xgb  458        130  0.664892  0.487121
272              Usage40_rf  458        130  0.653799  0.486982
273            No FIP28_xgb  458        130  0.722092  0.486285
274         Velo + FIP29_rf  458        130  0.682458  0.485971
275           Residuals1_rf  458        130  0.680746  0.485510
276            No FIP42_xgb  458        130  0.697795  0.485159
277         Velo + FIP23_rf  458        130  0.656731  0.485049
278          Residuals32_rf  458        130  0.691276  0.484159
279             Usage21_xgb  458        130  0.675211  0.483520
280         Velo + FIP36_rf  458        130  0.680840  0.483193
281   Regular Movement1_xgb  458        130  0.705019  0.482825
282        Velo + FIP12_xgb  458        130  0.666463  0.482395
283            No FIP41_xgb  458        130  0.717308  0.481890
284           Residuals8_rf  458        130  0.699859  0.481795
285   Regular Movement40_rf  458        130  0.691159  0.481578
286   Regular Movement47_rf  458        130  0.697936  0.481225
287          Residuals19_rf  458        130  0.693152  0.480905
288          Residuals13_rf  458        130  0.708677  0.480826
289              Usage1_xgb  458        130  0.678189  0.480734
290            No FIP13_xgb  458        130  0.710507  0.480374
291              Usage23_rf  458        130  0.649484  0.480251
292            No FIP23_xgb  458        130  0.712359  0.479972
293          Residuals3_xgb  458        130  0.686093  0.479833
294   Regular Movement15_rf  458        130  0.701313  0.479766
295         Velo + FIP18_en  458        130  0.680206  0.478840
296             No FIP5_xgb  458        130  0.693035  0.478656
297              Usage44_rf  458        130  0.659334  0.478132
298          Residuals23_rf  458        130  0.704339  0.477639
299         Velo + FIP13_rf  458        130  0.681168  0.477085
300         Velo + FIP20_rf  458        130  0.665361  0.476086
301              Usage26_rf  458        130  0.662946  0.475230
302          Residuals20_rf  458        130  0.710530  0.474895
303         Velo + FIP9_xgb  458        130  0.658326  0.472641
304              Usage9_xgb  458        130  0.650235  0.472207
305              Usage32_rf  458        130  0.659428  0.471764
306             No FIP6_xgb  458        130  0.715455  0.471339
307   Regular Movement44_rf  458        130  0.689611  0.471123
308          Residuals43_rf  458        130  0.696928  0.470947
309               Usage1_rf  458        130  0.631473  0.470849
310  Regular Movement21_xgb  458        130  0.703072  0.470686

In [20]:
two_year_breakout_df = helpy.is_breakout(base_analysis.results_df, .15, 100, 2)
base_analysis.get_model_metrics(df=two_year_breakout_df)

                      Model    N  Breakouts   ROC-AUC    PR-AUC
0                No FIP5_en  458         76  0.737738  0.405858
1                No FIP4_en  458         76  0.737634  0.405844
2                No FIP3_en  458         76  0.737565  0.405679
3                No FIP1_en  458         76  0.737359  0.403755
4                No FIP2_en  458         76  0.737359  0.403750
5               No FIP11_en  458         76  0.738392  0.403747
6                No FIP0_en  458         76  0.737255  0.402329
7               No FIP10_en  458         76  0.738289  0.402105
8            Residuals27_rf  458         76  0.739563  0.401196
9                No FIP9_en  458         76  0.737979  0.398058
10              No FIP24_rf  458         76  0.734155  0.394561
11              No FIP46_rf  458         76  0.733398  0.393345
12              No FIP30_rf  458         76  0.731021  0.392671
13               No FIP8_en  458         76  0.736704  0.392100
14           Residuals29_rf  458         76  0.713764  0.391742
15               No FIP7_en  458         76  0.736808  0.391646
16              No FIP27_rf  458         76  0.735533  0.390616
17               No FIP6_en  458         76  0.736153  0.390013
18    Regular Movement41_rf  458         76  0.714419  0.387759
19              No FIP17_en  458         76  0.733983  0.385681
20               No FIP5_rf  458         76  0.732123  0.384914
21              No FIP41_rf  458         76  0.728093  0.383859
22               Usage46_rf  458         76  0.707909  0.383134
23            Residuals5_rf  458         76  0.733191  0.381900
24              No FIP16_en  458         76  0.731193  0.381799
25              No FIP12_rf  458         76  0.721583  0.380637
26                Usage5_rf  458         76  0.712903  0.380624
27           Residuals25_rf  458         76  0.694475  0.379589
28    Regular Movement46_rf  458         76  0.724890  0.378129
29              No FIP15_en  458         76  0.728782  0.377989
30           Residuals30_rf  458         76  0.735602  0.377310
31           Residuals36_rf  458         76  0.711284  0.376732
32              No FIP14_rf  458         76  0.719379  0.374659
33              No FIP43_rf  458         76  0.727714  0.374144
34           Residuals41_rf  458         76  0.712524  0.373980
35              No FIP15_rf  458         76  0.723925  0.373893
36              No FIP19_rf  458         76  0.725200  0.373655
37              No FIP48_rf  458         76  0.720756  0.373569
38              No FIP18_rf  458         76  0.726853  0.373509
39              No FIP29_rf  458         76  0.725544  0.373420
40              No FIP36_rf  458         76  0.724235  0.371547
41              No FIP47_rf  458         76  0.726199  0.370918
42              No FIP13_rf  458         76  0.725028  0.369418
43              No FIP20_rf  458         76  0.717415  0.368662
44    Regular Movement30_rf  458         76  0.725131  0.368159
45               Usage11_rf  458         76  0.706359  0.367846
46              No FIP14_en  458         76  0.726715  0.366551
47    Regular Movement24_rf  458         76  0.724063  0.364042
48              No FIP13_en  458         76  0.726371  0.363383
49           Residuals24_rf  458         76  0.730504  0.362392
50    Regular Movement27_rf  458         76  0.724235  0.360576
51              No FIP7_xgb  458         76  0.726302  0.360415
52          Velo + FIP27_rf  458         76  0.703052  0.360152
53               Usage18_rf  458         76  0.693407  0.360127
54     Regular Movement5_rf  458         76  0.722169  0.359289
55              No FIP3_xgb  458         76  0.719551  0.358982
56             No FIP29_xgb  458         76  0.727370  0.358935
57              No FIP12_en  458         76  0.726130  0.358861
58               Usage29_rf  458         76  0.691719  0.357194
59               No FIP3_rf  458         76  0.719138  0.356782
60              No FIP25_rf  458         76  0.720309  0.356619
61           Residuals18_rf  458         76  0.715211  0.356592
62               Usage30_rf  458         76  0.701330  0.356174
63    Regular Movement36_rf  458         76  0.702053  0.355976
64               Usage36_rf  458         76  0.692684  0.355743
65             No FIP22_xgb  458         76  0.718001  0.355525
66              No FIP32_rf  458         76  0.719620  0.354820
67              No FIP1_xgb  458         76  0.716623  0.354013
68           Residuals15_rf  458         76  0.704671  0.353346
69           Residuals14_rf  458         76  0.706496  0.352574
70               Usage47_rf  458         76  0.682523  0.352478
71    Regular Movement13_rf  458         76  0.699952  0.352315
72               Usage48_rf  458         76  0.674428  0.351755
73               Usage27_rf  458         76  0.709424  0.351060
74              No FIP11_rf  458         76  0.724855  0.350983
75               Usage41_rf  458         76  0.691857  0.350424
76           Residuals48_rf  458         76  0.705187  0.349429
77    Regular Movement29_rf  458         76  0.701502  0.349289
78           Residuals46_rf  458         76  0.723168  0.348820
79             No FIP26_xgb  458         76  0.725648  0.348688
80               Usage24_rf  458         76  0.702845  0.348616
81              No FIP40_rf  458         76  0.718862  0.348029
82             No FIP48_xgb  458         76  0.712696  0.347790
83             No FIP45_xgb  458         76  0.720481  0.347247
84          Velo + FIP30_rf  458         76  0.698471  0.346997
85    Regular Movement11_rf  458         76  0.699573  0.346989
86           Residuals32_rf  458         76  0.690824  0.345703
87               Usage15_rf  458         76  0.686794  0.345245
88             No FIP47_xgb  458         76  0.716623  0.345217
89             No FIP40_xgb  458         76  0.727749  0.344674
90              No FIP34_rf  458         76  0.702122  0.343234
91              No FIP38_rf  458         76  0.708012  0.342558
92              No FIP26_rf  458         76  0.718655  0.342270
93              No FIP44_rf  458         76  0.718793  0.342068
94           Residuals47_rf  458         76  0.699573  0.342068
95             No FIP14_xgb  458         76  0.721962  0.341965
96             No FIP31_xgb  458         76  0.701226  0.341620
97    Regular Movement18_rf  458         76  0.698608  0.341583
98             No FIP21_xgb  458         76  0.727370  0.340980
99             No FIP34_xgb  458         76  0.726681  0.340649
100            No FIP16_xgb  458         76  0.714729  0.340235
101            No FIP35_xgb  458         76  0.710044  0.340056
102         Velo + FIP23_rf  458         76  0.643945  0.338715
103             No FIP31_rf  458         76  0.707977  0.338165
104            No FIP39_xgb  458         76  0.726784  0.338072
105             No FIP8_xgb  458         76  0.717656  0.337790
106              No FIP1_rf  458         76  0.711009  0.337725
107            No FIP12_xgb  458         76  0.711181  0.337675
108            No FIP19_xgb  458         76  0.725544  0.337591
109             No FIP23_rf  458         76  0.715245  0.337477
110              Usage43_rf  458         76  0.668917  0.337404
111             No FIP39_rf  458         76  0.706841  0.336471
112   Regular Movement7_xgb  458         76  0.703775  0.336367
113         Residuals21_xgb  458         76  0.711319  0.336192
114          Velo + FIP5_rf  458         76  0.697162  0.335284
115            No FIP18_xgb  458         76  0.706324  0.334407
116             No FIP16_rf  458         76  0.699745  0.334361
117            No FIP15_xgb  458         76  0.721101  0.333105
118            No FIP44_xgb  458         76  0.725165  0.332900
119            No FIP49_xgb  458         76  0.717105  0.332642
120              No FIP8_rf  458         76  0.715624  0.332078
121              Usage12_rf  458         76  0.681076  0.331551
122             No FIP45_rf  458         76  0.705463  0.331141
123   Regular Movement47_rf  458         76  0.692029  0.330639
124          Residuals8_xgb  458         76  0.705980  0.330372
125              No FIP2_rf  458         76  0.695887  0.330334
126              Usage7_xgb  458         76  0.702604  0.330325
127             No FIP9_xgb  458         76  0.698367  0.330272
128         Residuals14_xgb  458         76  0.718931  0.329705
129             No FIP18_en  458         76  0.713385  0.329598
130              Usage25_rf  458         76  0.688998  0.329400
131            No FIP27_xgb  458         76  0.698264  0.329298
132         Velo + FIP18_rf  458         76  0.669089  0.329079
133          Residuals19_rf  458         76  0.688275  0.328619
134          Residuals7_xgb  458         76  0.712765  0.328486
135             No FIP0_gam  458         76  0.688929  0.328267
136            No FIP30_xgb  458         76  0.730711  0.327779
137          Residuals1_xgb  458         76  0.691134  0.327077
138             No FIP19_en  458         76  0.712627  0.326439
139             No FIP2_xgb  458         76  0.708391  0.326123
140              Usage20_rf  458         76  0.652039  0.325487
141   Regular Movement15_rf  458         76  0.686277  0.325346
142             No FIP33_rf  458         76  0.682282  0.324825
143         Velo + FIP41_rf  458         76  0.668297  0.324798
144            No FIP36_xgb  458         76  0.713316  0.324504
145            No FIP10_xgb  458         76  0.697575  0.324032
146          Residuals11_rf  458         76  0.703810  0.323923
147         Velo + FIP29_rf  458         76  0.664853  0.323790
148  Regular Movement14_xgb  458         76  0.712903  0.323711
149             No FIP20_en  458         76  0.710699  0.322995
150              Usage19_rf  458         76  0.679216  0.322662
151         Velo + FIP46_rf  458         76  0.694268  0.322394
152              Usage8_xgb  458         76  0.709424  0.321871
153             No FIP22_en  458         76  0.708770  0.321747
154             No FIP21_en  458         76  0.709769  0.321741
155             Usage44_xgb  458         76  0.697782  0.320832
156              Usage14_rf  458         76  0.668952  0.320587
157          Residuals44_rf  458         76  0.697058  0.320161
158          Residuals43_rf  458         76  0.690721  0.320151
159             No FIP23_en  458         76  0.708460  0.319937
160             Usage14_xgb  458         76  0.700847  0.319763
161            No FIP32_xgb  458         76  0.696507  0.319625
162         Velo + FIP25_rf  458         76  0.663061  0.319619
163               Usage3_rf  458         76  0.672293  0.319454
164             No FIP49_rf  458         76  0.701536  0.319388
165          Residuals23_rf  458         76  0.701020  0.319049
166              Usage32_rf  458         76  0.659927  0.318843
167         Residuals12_xgb  458         76  0.679147  0.318324
168         Velo + FIP36_rf  458         76  0.666196  0.317938
169          Residuals20_rf  458         76  0.706565  0.317188
170         Velo + FIP7_xgb  458         76  0.695233  0.317104
171   Regular Movement14_rf  458         76  0.696748  0.316823
172         Velo + FIP11_rf  458         76  0.671087  0.316242
173          Residuals40_rf  458         76  0.692374  0.316103
174        Velo + FIP14_xgb  458         76  0.698057  0.315987
175          Residuals13_rf  458         76  0.689859  0.315932
176   Regular Movement32_rf  458         76  0.692339  0.315606
177   Regular Movement25_rf  458         76  0.693683  0.315160
178              Usage13_rf  458         76  0.682902  0.315058
179             No FIP37_rf  458         76  0.684521  0.314839
180             Usage39_xgb  458         76  0.688585  0.314634
181         Velo + FIP24_rf  458         76  0.688654  0.314336
182         Residuals39_xgb  458         76  0.700055  0.314165
183            No FIP28_xgb  458         76  0.712111  0.314031
184             No FIP21_rf  458         76  0.690996  0.313853
185   Regular Movement8_xgb  458         76  0.699504  0.313840
186            No FIP20_xgb  458         76  0.711560  0.312909
187           Baseline46_rf  458         76  0.710182  0.312301
188  Regular Movement21_xgb  458         76  0.691651  0.311516
189            No FIP17_xgb  458         76  0.722995  0.311449
190              No FIP9_rf  458         76  0.682729  0.311334
191           Baseline30_rf  458         76  0.708976  0.310827
192             No FIP6_xgb  458         76  0.715107  0.310590
193              Usage18_en  458         76  0.669365  0.309820
194              No FIP4_rf  458         76  0.694062  0.309490
195             No FIP10_rf  458         76  0.688861  0.309328
196             No FIP17_rf  458         76  0.704671  0.309123
197             No FIP22_rf  458         76  0.687931  0.308747
198              No FIP6_rf  458         76  0.690686  0.308665
199         Velo + FIP20_rf  458         76  0.656448  0.308624
200             Usage34_xgb  458         76  0.633405  0.307567
201           Residuals1_rf  458         76  0.660960  0.307529
202            No FIP33_xgb  458         76  0.705084  0.307184
203         Velo + FIP8_xgb  458         76  0.698540  0.306325
204            No FIP37_xgb  458         76  0.711697  0.306273
205  Regular Movement39_xgb  458         76  0.688137  0.306230
206   Regular Movement1_xgb  458         76  0.682282  0.306064
207             No FIP42_rf  458         76  0.687104  0.305396
208   Regular Movement48_rf  458         76  0.688861  0.305302
209            No FIP41_xgb  458         76  0.710492  0.305099
210           Residuals3_rf  458         76  0.681007  0.304807
211         Velo + FIP47_rf  458         76  0.660960  0.304783
212            No FIP24_xgb  458         76  0.707599  0.304494
213           Residuals8_rf  458         76  0.685761  0.304068
214   Regular Movement20_rf  458         76  0.683935  0.303748
215              No FIP0_rf  458         76  0.689205  0.303543
216          Residuals26_rf  458         76  0.688585  0.303328
217          Residuals12_rf  458         76  0.683349  0.303043
218        Velo + FIP44_xgb  458         76  0.691685  0.302949
219              No FIP7_rf  458         76  0.701915  0.302460
220              Usage23_rf  458         76  0.649180  0.300353
221              Usage1_xgb  458         76  0.688275  0.300169
222              Usage31_rf  458         76  0.643772  0.300106
223             No FIP35_rf  458         76  0.684934  0.299678
224         Velo + FIP48_rf  458         76  0.654657  0.299247
225             No FIP28_rf  458         76  0.683039  0.299199
226             No FIP5_xgb  458         76  0.683935  0.299086
227        Velo + FIP39_xgb  458         76  0.678837  0.299082
228         Velo + FIP14_rf  458         76  0.659893  0.298825
229   Regular Movement43_rf  458         76  0.680112  0.298812
230          Residuals3_xgb  458         76  0.673567  0.298340
231            No FIP38_xgb  458         76  0.700365  0.298131
232          Residuals25_en  458         76  0.697093  0.298076
233            No FIP23_xgb  458         76  0.712214  0.297872
234             No FIP24_en  458         76  0.699470  0.297696
235          Residuals24_en  458         76  0.698367  0.297572
236           Baseline24_rf  458         76  0.688309  0.297454
237   Regular Movement12_rf  458         76  0.681179  0.297224
238           Residuals6_rf  458         76  0.629926  0.297177
239         Velo + FIP25_en  458         76  0.696404  0.297145
240              Usage25_en  458         76  0.696404  0.297145
241           Baseline25_en  458         76  0.696404  0.297145
242   Regular Movement25_en  458         76  0.696404  0.297145
243           Baseline24_en  458         76  0.696163  0.297013
244              Usage19_en  458         76  0.664818  0.297005
245         Velo + FIP1_xgb  458         76  0.679767  0.296546
246        Velo + FIP35_xgb  458         76  0.629616  0.296423
247         Velo + FIP43_rf  458         76  0.649421  0.296358
248         Velo + FIP18_en  458         76  0.661201  0.296255
249    Regular Movement3_rf  458         76  0.677563  0.295892
250              Usage24_en  458         76  0.697437  0.295888
251          Velo + FIP3_rf  458         76  0.642842  0.295835
252          Residuals26_en  458         76  0.696301  0.295347
253           Baseline26_en  458         76  0.696301  0.295347
254              Usage26_en  458         76  0.696301  0.295347
255   Regular Movement26_en  458         76  0.696301  0.295347
256         Velo + FIP26_en  458         76  0.696301  0.295347
257          Residuals39_rf  458         76  0.662510  0.295253
258           Baseline27_rf  458         76  0.693683  0.295249
259             No FIP25_en  458         76  0.696990  0.295154
260         Velo + FIP29_en  458         76  0.696817  0.295125
261             No FIP26_en  458         76  0.696817  0.295125
262              Usage35_en  458         76  0.696817  0.295125
263              Usage31_en  458         76  0.696817  0.295125
264         Velo + FIP30_en  458         76  0.696817  0.295125
265         Velo + FIP33_en  458         76  0.696817  0.295125
266         Velo + FIP34_en  458         76  0.696817  0.295125
267          Residuals29_en  458         76  0.696817  0.295125
268          Residuals34_en  458         76  0.696817  0.295125
269          Residuals33_en  458         76  0.696817  0.295125
270          Residuals32_en  458         76  0.696817  0.295125
271   Regular Movement30_en  458         76  0.696817  0.295125
272           Baseline32_en  458         76  0.696817  0.295125
273           Baseline34_en  458         76  0.696817  0.295125
274             No FIP34_en  458         76  0.696817  0.295125
275              Usage32_en  458         76  0.696817  0.295125
276              Usage33_en  458         76  0.696817  0.295125
277              Usage34_en  458         76  0.696817  0.295125
278          Residuals31_en  458         76  0.696817  0.295125
279              Usage30_en  458         76  0.696817  0.295125
280             No FIP35_en  458         76  0.696817  0.295125
281             No FIP27_en  458         76  0.696817  0.295125
282             No FIP28_en  458         76  0.696817  0.295125
283          Residuals30_en  458         76  0.696817  0.295125
284              Usage29_en  458         76  0.696817  0.295125
285         Velo + FIP31_en  458         76  0.696817  0.295125
286         Velo + FIP32_en  458         76  0.696817  0.295125
287         Velo + FIP28_en  458         76  0.696817  0.295125
288         Velo + FIP35_en  458         76  0.696817  0.295125
289          Residuals35_en  458         76  0.696817  0.295125
290          Residuals28_en  458         76  0.696817  0.295125
291             No FIP29_en  458         76  0.696817  0.295125
292             No FIP31_en  458         76  0.696817  0.295125
293   Regular Movement34_en  458         76  0.696817  0.295125
294   Regular Movement33_en  458         76  0.696817  0.295125
295             No FIP33_en  458         76  0.696817  0.295125
296              Usage28_en  458         76  0.696817  0.295125
297             No FIP30_en  458         76  0.696817  0.295125
298             No FIP32_en  458         76  0.696817  0.295125
299   Regular Movement35_en  458         76  0.696817  0.295125
300   Regular Movement29_en  458         76  0.696817  0.295125
301           Baseline31_en  458         76  0.696817  0.295125
302           Baseline29_en  458         76  0.696817  0.295125
303           Baseline30_en  458         76  0.696817  0.295125
304   Regular Movement32_en  458         76  0.696817  0.295125
305   Regular Movement31_en  458         76  0.696817  0.295125
306           Baseline33_en  458         76  0.696817  0.295125
307           Baseline35_en  458         76  0.696817  0.295125
308           Baseline28_en  458         76  0.696817  0.295125
309   Regular Movement28_en  458         76  0.696817  0.295125
310           Baseline27_en  458         76  0.696680  0.294668

In [21]:
noFIP_predictions = base_analysis.predictors['No FIP'].predictions
nofip5_en = [d for d in noFIP_predictions if d.get("model_name") == "No FIP5_en"]
nofip11_en = [d for d in noFIP_predictions if d.get("model_name") == "No FIP11_en"]
nofip27_rf = [d for d in noFIP_predictions if d.get("model_name") == "No FIP27_rf"]
nofip7_xgb = [d for d in noFIP_predictions if d.get("model_name") == "No FIP7_xgb"]


residuals_predictions = base_analysis.predictors['Residuals'].predictions
residuals24_rf = [d for d in residuals_predictions if d.get("model_name") == "Residuals24_rf"]
residuals21_xgb = [d for d in residuals_predictions if d.get("model_name") == "Residuals21_xgb"]

In [22]:
print(f'no FIP 5 Elastic Net hyperparameters: {nofip5_en[0]['hyperparameters']}')
print(f'no FIP 11 Elastic Net hyperparameters: {nofip11_en[0]['hyperparameters']}')
print(f'no FIP 27 Random Forest hyperparameters: {nofip27_rf[0]['hyperparameters']}')
print(f'Residuals Random Forest hyperparameters: {residuals24_rf[0]['hyperparameters']}')
print(f'no FIP 27 XGBoost hyperparameters: {nofip7_xgb[0]['hyperparameters']}')
print(f'Residuals XGBoost hyperparameters: {residuals21_xgb[0]['hyperparameters']}')

no FIP 5 Elastic Net hyperparameters: {'l1_ratio': 1.0, 'alpha': 0.001}
no FIP 11 Elastic Net hyperparameters: {'l1_ratio': 1.0, 'alpha': 0.01}
no FIP 27 Random Forest hyperparameters: {'n_estimators': 500, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 5}
Residuals Random Forest hyperparameters: {'n_estimators': 200, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 5}
no FIP 27 XGBoost hyperparameters: {'subsample': 0.8, 'reg_lambda': 20, 'reg_alpha': 1, 'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.01, 'colsample_bytree': 0.6}
Residuals XGBoost hyperparameters: {'subsample': 1.0, 'reg_lambda': 10, 'reg_alpha': 1, 'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.03, 'colsample_bytree': 0.6}